### ISSUE TITLE
APKs signed with debug key?

### ISSUE THREAD

**Issue by IzzySoft** [vicolo-dev/chrono#1]
Your APKs are signed using a debug key:

```
package: name='com.vicolo.chrono' versionCode='2001' versionName='0.2.3' platformBuildVersionName='13' platformBuildVersionCode='33' compileSdkVersion='33' compileSdkVersionCodename='13'
Verifies
Verified using v1 scheme (JAR signing): true
Verified using v2 scheme (APK Signature Scheme v2): true
Verified using v3 scheme (APK Signature Scheme v3): false
Number of signers: 1
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: e7df19022bd6685987d92a5543c1b786e143536c5ffbed811e4a724d5db9ffaf
Signer #1 certificate SHA-1 digest: c9ba2763f3bcf282b0b2e7624e522f9fe7a32606
Signer #1 certificate MD5 digest: 60d3612514bd25b69eb0369139680b4f
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

It would be preferable to use your own release key for signing. Have you considered that?

**Comment by AhsanSarwar45** [comment]
Yes, I've signed them now, are they OK?

**Comment by AhsanSarwar45** [comment]
@IzzySoft Thanks. Uploaded the screenshots. 

But I am confused on what the next steps are since I have never uploaded to FDroid before. Should I create the merge request next? I have followed the [merge request guide](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests) and written a metadata file. But I am facing some uses when I push it to my fork (CI is failing). I have created an issue [here](https://forum.f-droid.org/t/fdroid-build-and-checksupdate-failing-in-ci/24511). Maybe you can help? 😄

And I am guessing after CI is passing, I compare the apks in my Github release to the one created by the CI using diffoscope? If there is no difference, that means the build is reproducible?

**Comment by IzzySoft** [comment]
> Uploaded the screenshots.

Thanks! Enabled them on my end, manually triggered a "fastlane pull" – they'll show up with the next sync then.

> But I am confused on what the next steps are since I have never uploaded to FDroid before.

For a "quick guide", you can take a look at my snippet under [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid). I'm currently not active at F-Droid, so I cannot help out at their end.

As for reproducible builds: yes, basically. If you need details on those:

* [HOWTO: diff & fix APKs for Reproducible Builds](https://gitlab.com/fdroid/wiki/-/wikis/HOWTO:-diff-&-fix-APKs-for-Reproducible-Builds)
* [Reproducible builds, signing keys, and binary repos](https://f-droid.org/2023/09/03/reproducible-builds-signing-keys-and-binary-repos.html)

Concerning your versioning, I'm a bit confused about this line in your `pubspec.yaml`:

```yaml
version: 0.2.5+1
```

That basically means you're still setting `versionCode` to `1` (and indeed, your arm64 build carries "2001"). This will need multiple adjustments: first, each release must have `versionCode` increased. Second, if you wish to ship multiple ABIs at F-Droid, you cannot use Flutter's defaults for that (which puts the ABI at the highest bit, e.g. adds 2000 for arm64) but need to have the ABI at the lowest bit, e.g. `versionCode * 10 + ABI` to add 1 for armeabi, 2 for arm64 – turning `0.2.5+1` into 21 and 22 respectively. I don't remember how that's done, I'm not an Android or Flutter developer – I just know it is possible. Some of the other Flutter apps at F-Droid might give you a clue at that.

**Comment by AhsanSarwar45** [comment]
> Concerning your versioning, I'm a bit confused about this line in your `pubspec.yaml`:
> 
> ```yaml
> version: 0.2.5+1
> ```
> 
> That basically means you're still setting `versionCode` to `1` (and indeed, your arm64 build carries "2001"). This will need multiple adjustments: first, each release must have `versionCode` increased. Second, if you wish to ship multiple ABIs at F-Droid, you cannot use Flutter's defaults for that (which puts the ABI at the highest bit, e.g. adds 2000 for arm64) but need to have the ABI at the lowest bit, e.g. `versionCode * 10 + ABI` to add 1 for armeabi, 2 for arm64 – turning `0.2.5+1` into 21 and 22 respectively. I don't remember how that's done, I'm not an Android or Flutter developer – I just know it is possible. Some of the other Flutter apps at F-Droid might give you a clue at that.


Thank you! I fixed the versioning issue to what you suggested as well.

Currently facing some issues in getting the builds to be reproducible but working on that.

**Comment by IzzySoft** [comment]
> I fixed the versioning issue to what you suggested as well.

Great, thanks! That will make it easier to switch between armeabi and arm64, both directions (e.g. to some 32bit backup device while the 64bit one is in for repair). For this one time it will mean people having installed it from my repo will have to uninstall and reinstall (as `versionCode` decreased), but that won't affect too many people as you acted right away. Would have been harder had we waited a couple of weeks. And was needed for F-Droid.org anyway :man_shrugging:

> Currently facing some issues in getting the builds to be reproducible but working on that.

That Howto-link above will be a great help with that. Helped me more than once, and I'm very thankful to @obfusk for providing it! You can find [the original here](https://gist.github.com/obfusk/f0460dcdb21396ba3d2cc9db56bb40ae) which probably will receive updates earlier (should there be any), as Fay is the expert on that.
