### ISSUE TITLE
custom ringtone - shuffle

### ISSUE THREAD

**Issue by Ruboka** [vicolo-dev/chrono#100]
**Is your feature request related to a problem? Please describe.**
Can't select custom ringtones.

**Describe the solution you'd like**
If custom ringtones get added I would like to have the option to select an folder or maybe more to be used as a source for alarms. If a alarm rings I want the option that each time it selects a file from the previously defined folders randomly which then gets played.

**Comment by ProfessorSparrs** [comment]
I too want to be able to choose my own sounds, I missed all my alarms today if even the app was working then. Ive followed the guide to a T to make it work 24/7

**Comment by AhsanSarwar45** [comment]
Custom ringtones have been added in 0.3.0. Although currently, you can only add files rather than folders. So I'll keep this open.

**Comment by AhsanSarwar45** [comment]
> I too want to be able to choose my own sounds, I missed all my alarms today if even the app was working then. Ive followed the guide to a T to make it work 24/7

Can you create an issue with device and android info if alarms didn't ring for you?

**Comment by Ruboka** [comment]
> Custom ringtones have been added in 0.3.0. Although currently, you can only add files rather than folders. So I'll keep this open.

nice thank you for this update. if the shuffle and folder feature gets implemted it will be awesome.

**Comment by AhsanSarwar45** [comment]
Option to select folders have been added in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). If you face any issues with it, or have any feedback, consider creating a new issue.
