### ISSUE TITLE
Add notifications for alarm, timer and stop watch

### ISSUE THREAD

**Issue by gun4qmm7h** [vicolo-dev/chrono#101]
Can we add notification like how google clock has it?

**Comment by AhsanSarwar45** [comment]
Hi, can you clarify what you mean?

**Comment by gun4qmm7h** [comment]
For the clock can we add a notification when its close to going off. And for timer, how much time is left. And for the stopwatch how long it has been going for

**Comment by AhsanSarwar45** [comment]
This is available in beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5. Please test it out to see if there are any issues.
