### ISSUE TITLE
Opening "Alarm" from quick settings causes the upcoming alarm to go off

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#103]
**Describe the bug**
If you have an alarm enabled and you try to open the app using the quick settings tile, you cause the upcoming alarm to go off

**To Reproduce**
1. enable an alarm
2. open quick settings(by swiping down from top)
3. click the alarm tile
4. the alarm goes of irrespective of the time
 
**Expected behavior**
the app should open normally

**Smartphone Information**
 - Device: [Sparx neo 7]
 - OS: [Android 12]
 - App version [0.2.10]

**Comment by AhsanSarwar45** [comment]
This should be fixed in beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5. Please test it out to see if this issue persists.
