### ISSUE TITLE
alarm date gets moved back when exiting app

### ISSUE THREAD

**Issue by saus23** [vicolo-dev/chrono#105]
**Describe the bug**
when I set the alarm for a future date (monday 1/29/2024) and exit the app, coming back to the app now shows the alarm set for the day before (1/28/2024)

I just tried with a test alarm set for today that bugged out (displayed yesterday's date) but it still went off. Unsure now if I should be choosing my alarm dates one day ahead or not.

update: seems to just be a visual bug, I set a test alarm for tomorrow but it did not trigger today (although the app now showed today's date)

**Smartphone Information**
 - Device: google pixel 7a
 - OS: android 14 / grapheneOS
 - App version: 0.2.10

**Comment by AhsanSarwar45** [comment]
Can you try with 0.3.0 release?

**Comment by saus23** [comment]
I've been using the fdroid repo on my phone, 0.3.0 hasn't hit there yet

**Comment by AhsanSarwar45** [comment]
I'm closing this for now. Feel free to to re-open if you encounter this again.
