### ISSUE TITLE
Add an option to lower the alarm volume while alarm tasks are being completed.

### ISSUE THREAD

**Issue by radioactiveSue** [vicolo-dev/chrono#108]
I would like to have the option in the settings to have the alarm volume lowered for a set amount of time while alarm tasks are open and a button to refill the timer during those tasks. 
Something similar to how Challenges Alarm Clock by Garage App Co and Sleep as Android: Smart Alarm by Petr Nálevka (Urbandroid) have their task timers set up.

**Comment by Roccovdberg** [comment]
Hi! My name is Rocco and I am a student from the Netherlands, for a school project I need to contribute to an open source project, so I would like to work on this issue, it is my first time of contributing to an open source project, but I think I can do this, may I work on this issue?

**Comment by AhsanSarwar45** [comment]
> Hi! My name is Rocco and I am a student from the Netherlands, for a school project I need to contribute to an open source project, so I would like to work on this issue, it is my first time of contributing to an open source project, but I think I can do this, may I work on this issue?

Hi Rocco, glad to see your interest in contributing to this. But I have already added this feature, and it will be out in the next release. But feel free to tackle any other issue you would like :)

**Comment by AhsanSarwar45** [comment]
This should be added in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). You can reduce task volume by going to Customize > Sounds and vibration > Volume while solving tasks. Currently, it automatically reduces the volume to the amount you set when tasks appear. If you encounter any issues with it or have feedback, consider creating a new issue.
