### ISSUE TITLE
Upcoming Alarm Notification

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#109]
**Is your feature request related to a problem? Please describe.**
Please add an alarm notification for upcoming alarms and also an alarm off option.

**Describe the solution you'd like**
Just show the current notification before some time ago (like 5 min ago)
**Describe alternatives you've considered**

**Additional context**

**Comment by AhsanSarwar45** [comment]
This is available in beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5. Please test it out to see if there are any issues.

**Comment by iBabu007** [comment]
It works well but If you turn off any alarm then it also shows upcoming alarm notification.
And Please add solved to dismissed option or snooze option only because if skip alarm option is shown then everyone try to skip it.

**Comment by AhsanSarwar45** [comment]
> It works well but If you turn off any alarm then it also shows upcoming alarm notification. And Please add solved to dismissed option or snooze option only because if skip alarm option is shown then everyone try to skip it.

Should be fixed in [beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta2). See if the issue persists.
