### ISSUE TITLE
is this useable for IOS?

### ISSUE THREAD

**Issue by goldenmoon67** [vicolo-dev/chrono#110]
is this useable for IOS?

**Comment by azeem-io** [comment]
Unfortunately, it is not compatible with iOS at the moment, and there are currently no plans to make it so. However, we appreciate your interest, and we encourage you to stay tuned for updates. Fingers crossed for potential developments in the future!

**Comment by AhsanSarwar45** [comment]
iOS support is not on my radar but if anyone is interested in adding support, its very welcome. Mainly, the alarm and timer features use android specific code so they will need to be ported. Apart from that, all other functionality should work.
