### ISSUE TITLE
Question on permissions

### ISSUE THREAD

**Issue by IzzySoft** [vicolo-dev/chrono#116]
My scanner just reported on your latest APK:

```
! repo/com.vicolo.chrono_12.apk declares sensitive permission(s):
  android.permission.SYSTEM_ALERT_WINDOW
! repo/com.vicolo.chrono_12.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Could you please clarify what this permission is needed for? Thanks in advance!

That `DEPENDENCY_INFO_BLOCK` is easy to avoid btw:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by AhsanSarwar45** [comment]
It WAS being used to show fullscreen overlays for alarm and timer functionality in very early prototype versions of the app. But I changed the logic so it might no longer be needed now. I will test to see if thats really the case. If yes, then I'll the permission in the next version.
I'll add the `DEPENDENCY_INFO_BLOCK` as well. Thanks!

**Comment by AhsanSarwar45** [comment]
Hi, released the new version, can you check if all is well now?

**Comment by IzzySoft** [comment]
Thanks! This indeed looks fine now :smiley: Both, the permission and the blob are gone. I'm closing this issue then. Thanks for your great support!
