### ISSUE TITLE
"Sort by.." for alarms

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#119]
**Describe the solution you'd like**
A button next to the settings, to sort alarms in different ways
• Day
• Date and time
• Order of Creation

**Describe alternatives you've considered**
Holding and sorting them manually

**Comment by Rafee-M** [comment]
+1 For this feature as well!

**Comment by AhsanSarwar45** [comment]
This has been added in the [v0.4.0-beta4](https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta4). Please test it out for any bugs and feedback.

**Comment by mizu-048** [comment]
instead of a separate option for descending and ascending for each sort option, i would recommend there be a second option to chose ascending or descending or we can alternate between ascending or descending by selecting an option twice

**Comment by mizu-048** [comment]
also i think it would be better if we first sort the enabled alarms and put them on the top and then we sort the disabled alarms and put them below enabled

**Comment by AhsanSarwar45** [comment]
> instead of a separate option for descending and ascending for each sort option, i would recommend there be a second option to chose ascending or descending or we can alternate between ascending or descending by selecting an option twice

Wouldn't that just another click the user has to do to sort? What benefits would it provide?

**Comment by mizu-048** [comment]
> Wouldn't that just another click the user has to do to sort? What benefits would it provide?

a cleaner sort menu

**Comment by AhsanSarwar45** [comment]
> > Wouldn't that just another click the user has to do to sort? What benefits would it provide?
> 
> a cleaner sort menu

Sure I'll consider that. But it would require restructuring of the select system, so it will probably come in a future update.

**Comment by mizu-048** [comment]
only a suggestions, the end result is your choice as the developer

**Comment by Rafee-M** [comment]
> This has been added in the [v0.4.0-beta4](https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta4). Please test it out for any bugs and feedback.

Works perfectly! Thanks!

**Comment by mizu-048** [comment]
• not a through examination due to my laziness but it resets to default after closing the app

• the highlight icon of sort when a different option is used makes it seem as if an option is enabled rather than preference being set.

• the filter button is useless, does nothing, probably a place holder for future work in progress features

**Comment by AhsanSarwar45** [comment]
> • not a thorough examination due to my laziness but it resets to default after closing the app

Currently, that is by design (mainly because thats the way I preferred to use it). But yes, I can see how most users would prefer for Sort to be a permanent preference rather than being a temporary option like the rest of filters. 

> • the filter button is useless, does nothing, probably a place holder for future work in progress features

I'm guessing you mean this button ![Screenshot_20240412-121023.jpg](https://github.com/vicolo-dev/chrono/assets/41967492/61241564-d1e3-4639-abd1-3d8299c019fa)

It is very much functional. Tapping it is supposed to show a list of actions that the user can do on the filtered set of items. If clicking on it does nothing, you can create an issue.
