### ISSUE TITLE
Some vendors appear twice.

### ISSUE THREAD

**Issue by Red6785** [vicolo-dev/chrono#12]
![Screenshot_20231215_113402](https://github.com/vicolo-dev/chrono/assets/88458171/88fa0ff9-e68c-438c-a860-cebba3f0c711)

**Comment by AhsanSarwar45** [comment]
Thanks. In the dontkillmyapp.com api, the extra ones refer to different manufacturers (HMD global for nokia etc.) but since both have the same instructions, I will filter the repeat ones out.
