### ISSUE TITLE
Give me the ability to translate your app into different languages (multi-language support)

### ISSUE THREAD

**Issue by Wjxfi** [vicolo-dev/chrono#120]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Sites usually used for semi-automatic translation FOSS apps: Hosted weblate (FOSS) & Crowdin (FOSSLESS)

**Comment by AhsanSarwar45** [comment]
Thanks, I've created a weblate project: https://hosted.weblate.org/projects/chrono/
It has components for both the app and fastlane (#121)
