### ISSUE TITLE
Translate app's F-droid description.

### ISSUE THREAD

**Issue by Wjxfi** [vicolo-dev/chrono#121]
**Is your feature request related to a problem? Please describe.**
No

Example (English & Russian):
https://f-droid.org/packages/nl.moeilijkedingen.jellyfinaudioplayer/
![6f7bd5ce-9114-4c70-931a-41f61f7ffd31.jpg](https://github.com/vicolo-dev/chrono/assets/113500363/d28d4514-736d-4bad-8983-1433f173e725)

**Comment by AhsanSarwar45** [comment]
Hi, you need to copy 
https://github.com/vicolo-dev/chrono/tree/master/fastlane/metadata/android/en-US into a new folder called `fastlane/metadata/android/ru/` or `fastlane/metadata/android/de-DE/` or whatever language you want, translate the `full_description` and `short_description` and create a pull request.

**Comment by AhsanSarwar45** [comment]
See #120
