### ISSUE TITLE
Backup all things

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#129]
**Is your feature request related to a problem? Please describe.**
Please add option to all backup not only themes but also alarms, timer etc.

**Describe the solution you'd like**
Just add check box type option
All            🔲
Themes  🔲
Settings  🔲
Clocks     🔲
Alarms    ✅
Timers    ✅

**Describe alternatives you've considered**

**Additional context**
It take too much time to set again all alarms Please add all items backup.

**Comment by mizu-048** [comment]
an example from [mihon](https://github.com/mihonapp/mihon):
![Screenshot_20240415-202425_1.png](https://github.com/vicolo-dev/chrono/assets/154871713/b9d498eb-eacc-469f-b02a-9ea57c8d01ab)

and although the request/enhancement is to add options to backup but i would like add that the backup currently does not include timers and alarms (probably more)

**Comment by AhsanSarwar45** [comment]
I've added this in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). Consider creating a new issue if you find any bugs.
