### ISSUE TITLE
Option to choose number of math questions

### ISSUE THREAD

**Issue by Rafee-M** [vicolo-dev/chrono#132]
**Is your feature request related to a problem? Please describe.**
Currently you can have multiple math questions to an alarm, but that requires adding it multiple times resulting in increased number of clicks

**Describe the solution you'd like**
A slider like in the 'Sequence' task section to set the number of math problems

**Describe alternatives you've considered**
Clicking multiple times and adding math problems

**Comment by AhsanSarwar45** [comment]
Should be added in v0.4.3. Feel free to create another issue if there are any problems with it.
