### ISSUE TITLE
App is not opening

### ISSUE THREAD

**Issue by ansarimohammed422** [vicolo-dev/chrono#137]
**Describe the bug**
App is not opening only

I just updated it from fdroid

**To Reproduce**

When i open the a0p it shows only black screen and ont opening

**Expected behavior**
I want the app to launch

**Screenshots**

![Screenshot_2024-03-27-04-01-54-589_com vicolo chrono](https://github.com/vicolo-dev/chrono/assets/78704469/2c909e52-01ec-4640-8bec-aef3d191f2d5)

This is wat happening

**Smartphone Information**
 - Device: [Poco x4 pro 5g indian variant]
 - OS: [ Android 13]
 - App version [e.g. 0.3.2]

**Additional context**

**Comment by AhsanSarwar45** [comment]
Hi, check out the latest release from Github releases, fdroid will take a little time to get the latest version.

**Comment by ansarimohammed422** [comment]
But the issue waas earlier fixed when i cleared apps data

**Comment by AhsanSarwar45** [comment]
Yes, because clearing data means there is nothing left to migrate from 0.2.10, so no errors. But for people who dont want to delete all their alarms and timers, I recommend not doing that and instead switching to versions 0.3.3 or higher.

**Comment by AhsanSarwar45** [comment]
I understand that this has been resolved so closing this. Feel free to re-open if the issue persists.
