### ISSUE TITLE
[Bug Report] Alarms Going Off When They Aren't Supposed To

### ISSUE THREAD

**Issue by MrCamel999** [vicolo-dev/chrono#150]
**Describe the bug**
My alarms set for specific dates went off today, 3/28, for seemingly no reason. I don't know why, but it ruined my plan to sleep in today. The option to skip the next occurance of the alarm also failed, which woke me up at 8:03. I did not want an alarm to go off today, but some bug caused *3* to go off. I'm not happy about it.

**To Reproduce**
I don't even know what specific steps to put, I'm just tired since I was woken up multiple times this morning by this bug.

**Expected behavior**
The alarms for 6:30 and 6:40 should only go off once, those being on the specified dates as seen in the below screenshots. Furthermore, the alarm set for 8:03 went off, despite me telling the app to skip the next occurance. Why this happened is beyond me, but none of these alarms should have gone off today.

**Screenshots**
![Screenshot_20240328-063104.png](https://github.com/vicolo-dev/chrono/assets/44412967/50febebb-7614-42c3-905a-91b152df9169)

![Screenshot_20240328-064023.png](https://github.com/vicolo-dev/chrono/assets/44412967/63aa6766-d43e-4841-b422-1ed8482cbb0b)

**Smartphone Information**
 - Device: [e.g. Samsung S10]
 - OS: [e.g. Android 13]
 - App version [e.g. 0.20]
Device: Sony Xperia 1 IV
OS: Android 14
Version: 0.3.4

**Additional context**
This is a very annoying problem, since I lost multiple hours of sleep this morning due to it.

**Comment by AhsanSarwar45** [comment]
Hi, really sorry for the inconvenience 😞. If you feel like it, can you test the latest beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5.

**Comment by AhsanSarwar45** [comment]
Closing this so all discussion can continue in this issue #154
