### ISSUE TITLE
 Alarm can't sound

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#153]
**Describe the bug**
If you add a new tone and then select it as alarm tone Alarm can't sound 
**To Reproduce**
1. Go to Setting 'Melody'
2.  Then add 'New tones'
3. Go to 'Alarm & Set any Newly added tone'
4. Alarm show on time without sound.

**Expected behavior**

**Screenshots**

**Smartphone Information**
 - Device: [e.g. ]
 - OS: [e.g. Android 10]
 - App version [v.0.3.4]

**Additional context**

**Comment by AhsanSarwar45** [comment]
Can you tell what kind of audio file that was? Also, did you change the volume or audio channel settings?

**Comment by iBabu007** [comment]
Now it work well but previous version selected tones are not ringing and can't delete.

**Comment by iBabu007** [comment]
Hi dev, Please add Contact info like email inside about section.

**Comment by iBabu007** [comment]
https://github.com/vicolo-dev/chrono/assets/65340361/55eb0563-3f3a-42c3-af1b-7de18a97075d

**Comment by AhsanSarwar45** [comment]
> Now it work well but previous version selected tones are not ringing and can't delete.

Cannot reproduce this. You can try clean installing.

> Hi dev, Please add Contact info like email inside about section.

Please create a new issue for this.
