### ISSUE TITLE
Off alarm's are ringing.

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#154]
**Describe the bug**
It's alarm is ring in wrong time.
**To Reproduce**
1. Go to 'alarm & set a alarm'
2. Then 'off it before time'
3. See 'alarm ringing'

**Expected behavior**

**Screenshots**

**Smartphone Information**
 - OS: [e.g. Android 10]
 - App version [v. 0.3.4]

**Additional context**

**Comment by AhsanSarwar45** [comment]
Can you test with the beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5

**Comment by AhsanSarwar45** [comment]
> I just installed it after uninstalling the old one, but the version in the app still shows as 0.3.4, is that normal? I just want to make sure I'm testing the app properly.

Should be OK. Forgot to bump version :P

**Comment by JetpackJackson** [comment]
Ok! I just tested it and it seemed to work fine, the alarms that were off didn't ring.

**Comment by iBabu007** [comment]
But there are more bugs.
If you turn off any alarm then it also shows upcoming alarm notification.

If you turn off any alarm it shows alarm is on but when you open it another time it shows same alarm is off.

**Comment by AhsanSarwar45** [comment]
Closing this for now then. If the issue crops back up, feel free to reopen it.
