### ISSUE TITLE
Starting timer in landscape layout is visually bugged

### ISSUE THREAD

**Issue by TheTrueWhiteOwl** [vicolo-dev/chrono#158]
**Describe the bug**
In landscape view, the time selection wheel is too big, hence half of the menu is offscreen and inaccessible.

**To Reproduce**
1. Go to the timer menu while in landscape view
2. Click on the plus icon to start a new timer
3. Observe how half of the timer wheel extends off-screen

**Expected behavior**
The menu should have all features accessible, whether in portrait or landscape mode.

**Screenshots**
![Screenshot_20240402_144904.jpg](https://github.com/vicolo-dev/chrono/assets/161154637/175a173b-a5a3-4781-92aa-55e41fb8e081)

**Smartphone Information**
 - Device: Samsung A51
 - OS: Android 13
 - App version 0.3.4

**Comment by AhsanSarwar45** [comment]
Should be fixed in v0.4.1. The new landscape UI doesn't look great, but atleast should be functional now. Will improve on it in coming versions. Let me know if you still face any issues.
