### ISSUE TITLE
Start melody at random position for waking up with natural sounds

### ISSUE THREAD

**Issue by JulScsl** [vicolo-dev/chrono#159]
**Is your feature request related to a problem? Please describe.**
I like to wake up to natural sounds like singing birds. I have several tracks, but over time, I know the start of each track by hearth which makes me wake up within a split second after the alarm went of.

**Describe the solution you'd like**
I'd like to have the option that the melody starts at a random point when the alarm goes off, so I can wake up a bit more smoothly.

**Describe alternatives you've considered**
Another possibility would be to play a random file from a folder/playlist. But that's a different use case for people who like to wake up to their favorite songs.

**Additional context**
I looked at dozens of alarm clocks, none has this feature. It would be a truly unique selling point.

**Comment by AhsanSarwar45** [comment]
Thanks for the request, I've added this in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). You can enable it by going to alarm settings > Sound and vibration > Random position. Consider creating a new issue if you find any bugs or have any feedback.
