### ISSUE TITLE
Version number not updated

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#161]
**Describe the bug**
The version number is still 0.3.4 in update 0.4.0-beta5

Which is why obtainium won't mark it as updated. 

**To Reproduce**
1. Install v0.3.4
2. Download and install Obtainium
3. Add chrono
4. Update it
5. Does not update
6. Version is still 0.3.4 even in the app but the new features have been added.

**Expected behavior**
Should update and show 0.4.0-beta5.

**Smartphone Information**
 - Device: [Sparx Neo 7]
 - OS: [Android 12]
 - App version [0.3.4/0.4.0]

**Additional context**
See https://github.com/octoshrimpy/quik/issues/40

**Comment by AhsanSarwar45** [comment]
Version number should be fixed in [beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta2) release.

**Comment by mizu-048** [comment]
@AhsanSarwar45 present in 0.4.0beta4

**Comment by AhsanSarwar45** [comment]
Thanks, updated. Should really automate this stuff.
