### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [vicolo-dev/chrono#163]
ref https://gitlab.com/fdroid/fdroiddata/-/jobs/6556379501#L1265 appears to say that even the tooling used was different :(

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/59161f0a77b6ef2860fa16f9907ec8ee4781609b

**Comment by AhsanSarwar45** [comment]
Could this be due to version name not being updated. I updated the build version, but forgot to change the version name (0.3.4). Because other than that, I made no change in the build process.

**Comment by licaon-kter** [comment]
versionName can be anything, ever the same for multiple versions. That's not it.

See the kotlin info on tooling differences... that's the bad part...

Maybe clean all caches, retry?

**Comment by AhsanSarwar45** [comment]
Latest release (0.4.0-beta3) is built after clearing github cache. How do I re-run fdroid build?

**Comment by licaon-kter** [comment]
thanks

**Comment by AhsanSarwar45** [comment]
The [0.4.0-beta4](https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta4) release doesn't give those warnings.

**Comment by licaon-kter** [comment]
built fine :) https://gitlab.com/fdroid/fdroiddata/-/jobs/6580541556/artifacts/browse/tmp/

**Comment by licaon-kter** [comment]
F-Droid is setup to pickup non-stable too, https://gitlab.com/fdroid/fdroiddata/-/blob/5aaaa4f2ab436c62b891eb1c607b1ac29005c7b3/metadata/com.vicolo.chrono.yml#L843

@AhsanSarwar45 do you want to skip them? Because I see you din;t publish APKs for them: https://gitlab.com/fdroid/fdroiddata/-/jobs/6830998158#L1301

**Comment by azeem-io** [comment]
I want to skip `-alpha` releases but not `-beta` ones, if that's possible to configure.

**Comment by AhsanSarwar45** [comment]
@licaon-kter I want to skip `-alpha` releases but not `-beta` ones, if its possible to configure it like so.

**Comment by licaon-kter** [comment]
@AhsanSarwar45 done https://gitlab.com/fdroid/fdroiddata/-/commit/1f377e828dc327fecb8c8fb10aa510186ff38e43

remember that it will skip `alpha` but not `alfa` or `Alpha` :smile:

**Comment by licaon-kter** [comment]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/6845968736#L1241

diffoscope says all is fine so...

using [diff-zip-meta.py](https://github.com/obfusk/reproducible-apk-tools?tab=readme-ov-file#diff-zip-metapy) for that file:
```

entry AndroidManifest.xml:
- CRC=0xa02001cd
+ CRC=0xd3c948c9
- compress_size=5635
+ compress_size=5646
- file_size=28616
+ file_size=28628
- header_offset=15687158
+ header_offset=15687026
- compress_crc=0xfe34f64d
+ compress_crc=0x7fd73fc5
```

@linsui CI APK: https://gitlab.com/fdroid/fdroiddata/-/jobs/6845968736/artifacts/file/tmp/com.vicolo.chrono_201.apk vs upstream: https://github.com/vicolo-dev/chrono/releases/download/v0.5.0-beta1/chrono-v0.5.0-beta1-armeabi-v7a.apk

**Comment by linsui** [comment]
I don't know why your diffoscope says all is fine but mine tells me that the version name is different. The version name of upstream apk is 0.5.0.

**Comment by AhsanSarwar45** [comment]
Thanks for pointing out, I've updated the binaries for the tag.

**Comment by licaon-kter** [comment]
Indeed, diffoscope takes a lot of time so I bypass it by disassembling the APKs by apktool first then compare the output.

The version is listed in a special `apktool.yml` file that I delete since it's (usually lol) not needed for the info I search.

I'll keep in mind to compare this too.

Thank

**Comment by licaon-kter** [comment]
@AhsanSarwar45 reenable: https://gitlab.com/fdroid/fdroiddata/-/commit/fdae796de894f097eef857f896338cd5ffe3f541

@linsui after posting my comment above I started diffoscope against the two APKs... it's still not yet done :(
