### ISSUE TITLE
Ghost alarms

### ISSUE THREAD

**Issue by hjek** [vicolo-dev/chrono#167]
**Describe the bug**
Chrono sets alarms that are not listed in the main app window but do trigger and are visible on lock screen and notification bar.

**To Reproduce**
1. Set an alarm for 10 AM every day.
2. At 10 AM, snooze the alarm a few times.
3. Disable the alarm, so there's just that one alarm and it's listed as "Not scheduled".
4. Even though there are allegedly no alarms scheduled, Chrono will trigger the alarm again and again, once for every time the alarm was snoozed. This non-listed alarm will go off repeatedly, even if it's dismissed, not snoozed.

**Expected behavior**
I expect the alarm to not go off when it's not scheduled. I expect the alarm to be not merely snoozed when clicking dismiss on an active alarm notification. I expect a way to see and edit all pending alarms.

**Smartphone Information**
 - Device: Nokia 2
 - OS: Android 11
 - App version: 0.3.4

**Comment by hjek** [comment]
Notice the alarm icon in the notification bar while according to the main window there are no actice alarms:

![Screenshot_20240410-102103](https://github.com/vicolo-dev/chrono/assets/11958965/fcd20ad8-a55f-4817-9bb0-caf21d8839e9)

The alarm kept going off while I was writing this bug report:

![Screenshot_20240410-103009](https://github.com/vicolo-dev/chrono/assets/11958965/c73b8298-98f6-48e8-bca2-84435a2be6c4)

**Comment by AhsanSarwar45** [comment]
This has been fixed in v0.4.0. It might take a couple of days for it to become available on fdroid but you can get it now from github releases. Although if the issue persists, you can re-open this.
