### ISSUE TITLE
[Bug] Date range going wild when scheduled 

### ISSUE THREAD

**Issue by potatocinna** [vicolo-dev/chrono#17]
Heya!

Love this app so much, can't thank you enough for that 🙏 The work is **insane**, I'm thrilled for the next updates

> About the bug, it's an issue in the alarms tab. The date range displays a long empty rectangular shape when the alarm is enabled, but it works well when it's not scheduled. Quite hard to explain it like that so hope you can see the pics below!

Thank you again 💫

![Screenshot_20231216-035224_Chrono.png](https://github.com/vicolo-dev/chrono/assets/122670684/cd9e3de1-6c42-426b-af9d-5fad5b12b4d7)

![Screenshot_20231216-035234_Chrono.png](https://github.com/vicolo-dev/chrono/assets/122670684/97438363-a9d7-4eca-8167-5b96d3a0035d)

![Screenshot_20231216-040101_Chrono.png](https://github.com/vicolo-dev/chrono/assets/122670684/26054c2a-9d34-4a43-b1a6-e9f195d2ff15)

(seems like Github on my phone doesn't want to add labels for who knows what reason, sorry about that!)

**Comment by AhsanSarwar45** [comment]
Hi, this should be fixed in the next release (0.2.8). Thanks for reporting this.

And glad that you like the app 😄
