### ISSUE TITLE
"On specific dates" is broken

### ISSUE THREAD

**Issue by STVGecko** [vicolo-dev/chrono#174]
**To Reproduce the bug**
1. Create an alarm, select a time
2. Click on Schedule >Type >On specific dates
3. Select one or more dates, then save the alarm
4. The alarm display "no future dates"  and don't work

![Screenshot_20240413_182911](https://github.com/vicolo-dev/chrono/assets/71868745/978087a4-07fc-47e9-b6c7-764bbeaa1db8)
![Screenshot_20240413_182922](https://github.com/vicolo-dev/chrono/assets/71868745/e0472847-6b9c-4337-be53-cf4366f644c9)

**Comment by AhsanSarwar45** [comment]
Thanks for the report. Should be fixed in v0.4.1.
