### ISSUE TITLE
Show current time using app icon clock hands

### ISSUE THREAD

**Issue by josb** [vicolo-dev/chrono#176]
It would be nice to see the app icon clock hands display the current time.
This may require changes to the app icon design to improve clarity as the current hands are relatively thick and short.

**Comment by AhsanSarwar45** [comment]
Unfortunately, only system apps can do that, and android doesn't provide any api for third-party apps for this.

**Comment by josb** [comment]
Bummer, wasn't aware. Thanks for letting me know.
