### ISSUE TITLE
Alarms getting duplicated

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#177]
**Describe the bug**
I enable some alarms, they rings and when i go to enable them again there are like two or three more of them. 

But here is the twist, the number of alarms is not changing and some of the duplicated alarms don't have the same melodies, indicating that the other alarms are transforming into the ones, I enabled

**To Reproduce**
1. "Sort by..."
2. enable some alarms( make sure you have some left disabled)
3. go to sleep
4. wake up to see multiple alarms

**Expected behavior**
No duplication/transforming should happe

**Smartphone Information**
 - Device: [Sparx Neo 7]
 - OS: [Android 12/ SDK 31]
 - App version []

**Additional context**
![tenor-3781584635.gif](https://github.com/vicolo-dev/chrono/assets/154871713/8bdc0362-1d9c-493c-8925-fd2cbe3c7e57)

**Comment by mizu-048** [comment]
![Screenshot_20240414-221732.png](https://github.com/vicolo-dev/chrono/assets/154871713/7f668bad-27a3-4b1a-9aea-73b18392b587)

![Screenshot_20240414-221555.png](https://github.com/vicolo-dev/chrono/assets/154871713/7ca09de4-06e0-4d1b-aa50-e4b24b1b90f0)

**Comment by AhsanSarwar45** [comment]
Thanks for the report. In trying to reproduce this, I also discovered some other weird issues when alarms are sorted. I think I have fixed them all, but will need to do more testing. Will release a beta after that so you can also test on your device.

**Comment by AhsanSarwar45** [comment]
Can you test with this dev version https://github.com/vicolo-dev/chrono/actions/runs/8709215981/artifacts/1418997843. While you are at it, also check if filter actions are working for you now.

**Comment by mizu-048** [comment]
before i can put it to a practical test, there is no option for custom melodies and the lack of alarms backup is not a good look when you have to reinstall the app

**Comment by AhsanSarwar45** [comment]
> before i can put it to a practical test, there is no option for custom melodies and the lack of alarms backup is not a good look when you have to reinstall the app

There is option for custom melodies. You have to go to Settings > General > Melodies.

Also, you don't have to uninstall the previous version to install the dev version. It installs as a separate version. As for the alarm backup feature, it will come eventually.

**Comment by mizu-048** [comment]
> There is option for custom melodies. You have to go to Settings > General > Melodies.

oh, i forgot. i thought it was in melody selection menu. thanks!
 
> Also, you don't have to uninstall the previous version to install the dev version. It installs as a separate version. As for the alarm backup feature, it will come eventually.

yes but  you still have to make the alarms again and set the melodies, as it does not have the app data of the orignal and you can't import them from backup


anyway i tested it over night and no duplication occured

**Comment by AhsanSarwar45** [comment]
Should be fixed in v0.4.1.
