### ISSUE TITLE
[Feature Request] Add skip next alarm to Filter Actions

### ISSUE THREAD

**Issue by Rafee-M** [vicolo-dev/chrono#181]
**Is your feature request related to a problem? Please describe.**
The Filter Actions are really convenient and make life so much easier. I believe adding a skip next alarm for selected filters would be even more helpful to the user. Thanks for all the work on the app!

**Describe the solution you'd like**
A skip next alarm button possibly above the enable and disable alarm buttons

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot_2024-04-18-06-22-39-18_10020bdc1efa12c4c1179522be8f36a1_1](https://github.com/vicolo-dev/chrono/assets/69535896/e96dd51c-70e0-496a-99f9-222a8a5acbc3)

**Comment by AhsanSarwar45** [comment]
Should be added in v0.4.1. Let me know if you face any issues.

**Comment by Rafee-M** [comment]
Thanks for the quick addition!
