### ISSUE TITLE
Hold and select alarms

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#186]
**Describe the solution you'd like**
Hold an alarm to enable selecting multiple alarms by a single clicking them. On the selected alarms batch operations can be performed like

• Deleting
• duplicating
• melody shuffle(#187)
• etc etc

**Comment by AhsanSarwar45** [comment]
This has been implemented. Should be 9ut in the next repease (0.6.0)

**Comment by AhsanSarwar45** [comment]
Should be out in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). Consider creating a new issue if you have any feedback or face any issues.
