### ISSUE TITLE
Add "add melody" option to the melody selection menu

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#188]
**Describe the solution you'd like**
Add an entry for "Add Melody" to the melody selection menu in the alarm edit window/panel/menu, so you don't have to go the settings. alternatively we can just redirect the user to the melody settings when this is pressed.

**Comment by AhsanSarwar45** [comment]
Thanks for the suggestion. I've added a '+' button in melody selection menu, which will take user to melody settings to add new melody for now.
