### ISSUE TITLE
Fix random numbers after custom melody file name

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#189]
**Describe the bug**
there is a rather big number at the end of custom melody filenames

**To Reproduce**
1. Add custom melody
2. there is a long number after the filename

**Expected behavior**
Only the name of the filename should be shown

**Screenshots**
![Screenshot_20240419-221907.png](https://github.com/vicolo-dev/chrono/assets/154871713/376e5e8a-8f34-4cd4-8db2-e05fabdf2ef9)

**Smartphone Information**
 - Device: [Sparx Neo 7]
 - OS: [Android 12/ SDK 31]
 - App version [v0.4.1]

**Comment by AhsanSarwar45** [comment]
Should be fixed in v0.4.3. Feel free to reopen if issue persists.
