### ISSUE TITLE
an alarm going off, disables the others

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#191]
**Describe the bug**
When an alarm goes off not all but most of the upcoming alarms are disabled

**To Reproduce**
1. Enable some alarms
2. Enable instant alarm button in develooer settings
3. Click instant alarm button
4. Alarms are disabled automatically once an alarm goes off

**Smartphone Information**
 - Device: [Sparx Neo 7]
 - OS: [Android 12/ SDK 31]
 - App version [0.4.1]

**Comment by AhsanSarwar45** [comment]
Thanks for reporting this. Luckily, fix was easy. Should be fixed wiyh 0.4.2. Let me know if it still pops up.
