### ISSUE TITLE
Option to make Sunday the first day

### ISSUE THREAD

**Issue by Turhvjbufv** [vicolo-dev/chrono#192]
**Is your feature request related to a problem? Please describe.**
Feels weird seeing Monday as the first day,
If it's not too much of a hassle please add an option to make Sunday the first day

**Comment by SA-Flipperwaldt** [comment]
I'd like an option to see Monday as the first day of the week when selecting a specific date, as is the style in my part of the world. I assume work on both of those goes hand in hand. 

Much appreciating the work so far as well as the visual style of the app.

**Comment by AhsanSarwar45** [comment]
This should be added in the [v0.5.0-beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta2) release. Go to Settings > General > Display > First Day of Week. Let me know if there are any issues with it.
