### ISSUE TITLE
Automatically delete alarm that are past their last date

### ISSUE THREAD

**Issue by Turhvjbufv** [vicolo-dev/chrono#197]
**Is your feature request related to a problem? Please describe.**
Alarm tab having many alarms that I set to a specific date and won't use anymore 

**Describe the solution you'd like**
Option to auto delete alarm that are past their last date

**Comment by AhsanSarwar45** [comment]
Thanks, this has been added in 0.4.3. Feel free to create an issue if there is any problem with it.
