### ISSUE TITLE
Correct answer to maths problem fails to work

### ISSUE THREAD

**Issue by curlpipe** [vicolo-dev/chrono#199]
**Describe the bug**
Occasionally, the alarm flat out fails to stop, even if the correct answer to the maths problem is given. It doesn't always happen. 

**To Reproduce**
1. Create alarm and add maths problem tasks (maybe try adding multiple of them to one alarm) 
2. Wait until alarm goes off
3. Try providing correct answer to dismiss alarm
4. Fails to dismiss

**Expected behavior**
The alarm dismisses after providing correct answers to the maths problems

**Screenshots**

![Screenshot_2024-04-26-11-05-34-02_10020bdc1efa12c4c1179522be8f36a1~2.jpg](https://github.com/vicolo-dev/chrono/assets/11898833/5cf7196d-f012-4fed-94e3-5a5a51e6526f)

**Smartphone Information**
 - Device: Oneplus 7 Pro
 - OS: Android 12
 - App version 0.4.1

**Comment by AhsanSarwar45** [comment]
Should be fixed in 0.4.3. Feel free to re-open if issue persists.

**Comment by curlpipe** [comment]
Thanks so much. This is a really great app so I'm really pleased that this has been fixed 👍
