### ISSUE TITLE
So many date fmts, and none of them iso-8601 😛

### ISSUE THREAD

**Issue by AeliusSaionji** [vicolo-dev/chrono#2]
![Screenshot-2023-12-14-14-50-31](https://github.com/vicolo-dev/chrono/assets/4342746/e465f338-e706-4f0f-8a09-9c51130fa549)

Please add YYYY-MM-DD !
https://www.iso.org/iso-8601-date-and-time-format.html

thanks

**Comment by ViktorKahu** [comment]
...and "d MMMM yyyy" - "15 December 2023"

**Comment by AhsanSarwar45** [comment]
Thanks, I'll add them right in.
