### ISSUE TITLE
Add option to show alarm title (label) when ringing and in notifications

### ISSUE THREAD

**Issue by computerinfo21** [vicolo-dev/chrono#200]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. I use a lot of alarms and sometimes have multiple ringing within a few minutes of each other. Since it just says alarm I don't know which one is ringing.Same issue with snoozed alarms (see screenshots).

**Describe the solution you'd like**
Would be awesome to have a setting to show the label. Either global or per-alarm.

**Describe alternatives you've considered**

**Additional context**
Screenshot of alarm ringing that doesn't show the label
![Screenshot_20240419-102941](https://github.com/vicolo-dev/chrono/assets/12566416/04d9b77f-810a-4a36-9abc-8e25312ccd13)
Example of snoozed alarm notification that doesn't show the label
![Screenshot_20240426-235402_Chrono](https://github.com/vicolo-dev/chrono/assets/12566416/de382a15-677a-433f-9b10-755c5cc012c6)

**Comment by AhsanSarwar45** [comment]
Added this in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). If you have any feedback, consider creating a new issue.
