### ISSUE TITLE
Add french translation pls

### ISSUE THREAD

**Issue by bdOtopsy63** [vicolo-dev/chrono#208]
Hi, this app is beautifull but plzase can you add french tranqlation please ?

I can make the translation for you if you want as im french and make french translation for Iconify app 👍

**Comment by AhsanSarwar45** [comment]
Sure, you can head over to https://hosted.weblate.org/projects/chrono/ to add French translations. Currently, its 33% done. Let me know of you need any other help.

**Comment by bdOtopsy63** [comment]
Hi,Nice, count on me will translate all the missing strings during the journey and will praise for a soon update for French language 😊Again really sleek and beautiful app man ♥️Have a very good day ☀️Mr. d’OliveiraLe 2 mai 2024 à 10:08, Ahsan Sarwar ***@***.***> a écrit :﻿
Sure, you can head over to https://hosted.weblate.org/projects/chrono/ to add French translations. Currently, its 33% done. Let me know of you need any other help.

**Comment by potatocinna** [comment]
Henlo everyone :wave: I'm fluent in both languages so I can help, will do that asap. Probably tonight or this weekend :> Have a nice day y'all.

**Comment by potatocinna** [comment]
Heya, I've had a few things things to do, sorry for the delay :> It should be approximately fine now. 

@bdOtopsy63 Bonjour, n'hésitez pas à vérifier la traduction, c'est toujours plus sûr d'avoir deux esprits qu'un seul. Bonne journée !

@AhsanSarwar45 When you have some time it'd be nice to add descriptions to more stuff, even when comparing with the app, it's sometimes tricky to guess the context right. It would make translation easier. Thank you for your hard work!

Have a lovely day everyone :tulip: 
![image](https://github.com/vicolo-dev/chrono/assets/122670684/9e13a26e-8256-4a95-a2f3-b595bdef8a7c)

**Comment by bdOtopsy63** [comment]
Hi,

Thanks have just checked and change 2/3 thing but now French translation is 100% completed 👌🏼👍🏼✌🏼 !
Just now need to update the app ah ah 😅
Can't wait tu use it in French by the way 🤞🏻🤞🏻🤞🏻
Have a very good day guys ☀️

**Comment by AhsanSarwar45** [comment]
@potatocinna @bdOtopsy63 
Thanks a lot for your contributions! Just added a few more strings, so now every string in the app should be available to translate on weblate.

And yes, I will start adding descriptions and screenshot to string to they are easier to translate.

**Comment by potatocinna** [comment]
Thank you for updating us!  I'll look at the new strings in a few hours  (˶˃ ᵕ ˂˶)

**Comment by bdOtopsy63** [comment]
Seems ok 👌🏼 Mr. d’OliveiraLe 7 mai 2024 à 15:00, Ahsan Sarwar ***@***.***> a écrit :﻿
@potatocinna @bdOtopsy63
Thanks a lot for your contributions! Just added a few more strings, so now every string in the app should be available to translate on weblate.
And yes, I will start adding descriptions and screenshot to string so they are easier to translate.

**Comment by bdOtopsy63** [comment]
Again French 100% translated with new string 👌🏼Mr. d’OliveiraLe 7 mai 2024 à 15:03, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Seems ok 👌🏼 Mr. d’OliveiraLe 7 mai 2024 à 15:00, Ahsan Sarwar ***@***.***> a écrit :﻿
@potatocinna @bdOtopsy63
Thanks a lot for your contributions! Just added a few more strings, so now every string in the app should be available to translate on weblate.
And yes, I will start adding descriptions and screenshot to string so they are easier to translate.

**Comment by bdOtopsy63** [comment]
Sir,Translation for French checked again > 100% done 👌🏼Mr. d’OliveiraLe 7 mai 2024 à 15:23, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Again French 100% translated with new string 👌🏼Mr. d’OliveiraLe 7 mai 2024 à 15:03, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Seems ok 👌🏼 Mr. d’OliveiraLe 7 mai 2024 à 15:00, Ahsan Sarwar ***@***.***> a écrit :﻿
@potatocinna @bdOtopsy63
Thanks a lot for your contributions! Just added a few more strings, so now every string in the app should be available to translate on weblate.
And yes, I will start adding descriptions and screenshot to string so they are easier to translate.

**Comment by AhsanSarwar45** [comment]
Thanks all. Tested the app using French and all looks good. Just one thing that maybe possible to change. It's for the string 'More'. The french translation is too long to be able to fit in the limited space available. I have added comments here https://hosted.weblate.org/translate/chrono/app/fr/?q=more&sort_by=-priority%2Cposition&checksum=. Also added a screenshot and updated explanation. Please see if its possible to shorten it.

**Comment by AhsanSarwar45** [comment]
English:
![image](https://github.com/vicolo-dev/chrono/assets/41967492/112ac08c-adb4-493f-aad3-fd08e66c541c)
French:
![image](https://github.com/vicolo-dev/chrono/assets/41967492/aa904f90-22ad-4140-a3f7-b668daed6e13)

**Comment by AhsanSarwar45** [comment]
In general try to translate the English text exactly. For example, when translating string 'Accent', you don't need to translate it into 'Couleur primaire & d’accent' (which google translate tells me means 'Primary & accent color'). The translation should just mean 'accent' or 'primary' or whatever the relevant translation is.

I need to add more screenshots to help translators get an idea of how much space is available.

Original:
![image](https://github.com/vicolo-dev/chrono/assets/41967492/d9852c1e-81c3-4ad7-9038-311653a181c1)

French (translation is too long)
![image](https://github.com/vicolo-dev/chrono/assets/41967492/5a5f5256-4f99-43cd-8ab6-7049d2e3ca28)

**Comment by bdOtopsy63** [comment]
Hi again,So again French is translated at 100% with the new strings and I changed More by « Plus » that is perfectly accurate for the function 👌🏼👍🏼Can’t wait to use the app in French it will be sooo cool ♥️Have all a very good day ☀️Mr. d’OliveiraLe 8 mai 2024 à 10:19, Ahsan Sarwar ***@***.***> a écrit :﻿
In general try to translate the English text exactly. For example, when translating string 'Accent', you don't need to translate it into 'Couleur primaire & d’accent' (which google translate tells me means 'Primary & accent color'). The translation should just mean 'accent' or 'primary' or whatever the relevant translation is.
I need to add more screenshots to help translators get an idea of how much space is available.
Original:
image.png (view on web)
French (translation is too long)
image.png (view on web)

**Comment by bdOtopsy63** [comment]
Hi,Nice news ♥️So I rechecked translations and made those who are missing 👌🏼Mr. d’OliveiraLe 13 mai 2024 à 19:35, Ahsan Sarwar ***@***.***> a écrit :﻿
Hi all, check out the v0.5.0-beta1 release. I added a few more strings and they are remaining to be translated, but we'll have 100% French translation by v0.5.0 stable.

**Comment by bdOtopsy63** [comment]
Hi,So I downloaded beta and change a word for better accuracy « Rings » > « Anneaux »See picture please 😊 ?Then the French translation is near perfect man 👍🏼Have a very good day ☀️Mr. d’OliveiraLe 14 mai 2024 à 09:09, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi,Nice news ♥️So I rechecked translations and made those who are missing 👌🏼Mr. d’OliveiraLe 13 mai 2024 à 19:35, Ahsan Sarwar ***@***.***> a écrit :﻿
Hi all, check out the v0.5.0-beta1 release. I added a few more strings and they are remaining to be translated, but we'll have 100% French translation by v0.5.0 stable.

**Comment by bdOtopsy63** [comment]
And for EU users on default clock screen it should be write « Jeudi 16 Mai » and not « Jeudi Mai 16 ».And it will be perfect 👍🏼 Mr. d’OliveiraLe 16 mai 2024 à 11:49, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi,So I downloaded beta and change a word for better accuracy « Rings » > « Anneaux »See picture please 😊 ?Then the French translation is near perfect man 👍🏼Have a very good day ☀️Mr. d’OliveiraLe 14 mai 2024 à 09:09, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi,Nice news ♥️So I rechecked translations and made those who are missing 👌🏼Mr. d’OliveiraLe 13 mai 2024 à 19:35, Ahsan Sarwar ***@***.***> a écrit :﻿
Hi all, check out the v0.5.0-beta1 release. I added a few more strings and they are remaining to be translated, but we'll have 100% French translation by v0.5.0 stable.

**Comment by bdOtopsy63** [comment]
Hi man,Excuse me will you release translated version soon please ?Mr. d’OliveiraLe 16 mai 2024 à 11:52, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿And for EU users on default clock screen it should be write « Jeudi 16 Mai » and not « Jeudi Mai 16 ».And it will be perfect 👍🏼 Mr. d’OliveiraLe 16 mai 2024 à 11:49, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi,So I downloaded beta and change a word for better accuracy « Rings » > « Anneaux »See picture please 😊 ?Then the French translation is near perfect man 👍🏼Have a very good day ☀️Mr. d’OliveiraLe 14 mai 2024 à 09:09, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi,Nice news ♥️So I rechecked translations and made those who are missing 👌🏼Mr. d’OliveiraLe 13 mai 2024 à 19:35, Ahsan Sarwar ***@***.***> a écrit :﻿
Hi all, check out the v0.5.0-beta1 release. I added a few more strings and they are remaining to be translated, but we'll have 100% French translation by v0.5.0 stable.

**Comment by bdOtopsy63** [comment]
Hi,Thanks for the beta 2 that fix translation 👌🏼Only remain the clock on the default screen: the date should be « Lundi 20 mai » not « Lundi Mai 20 » 😉Beside that app is sleek af ♥️Hope you could fix the date format.I wish you a very good day man ☀️Mr. d’OliveiraLe 19 mai 2024 à 13:56, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi man,Excuse me will you release translated version soon please ?Mr. d’OliveiraLe 16 mai 2024 à 11:52, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿And for EU users on default clock screen it should be write « Jeudi 16 Mai » and not « Jeudi Mai 16 ».And it will be perfect 👍🏼 Mr. d’OliveiraLe 16 mai 2024 à 11:49, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi,So I downloaded beta and change a word for better accuracy « Rings » > « Anneaux »See picture please 😊 ?Then the French translation is near perfect man 👍🏼Have a very good day ☀️Mr. d’OliveiraLe 14 mai 2024 à 09:09, Brice dOliveira ([#]b-do) ***@***.***> a écrit :﻿Hi,Nice news ♥️So I rechecked translations and made those who are missing 👌🏼Mr. d’OliveiraLe 13 mai 2024 à 19:35, Ahsan Sarwar ***@***.***> a écrit :﻿
Hi all, check out the v0.5.0-beta1 release. I added a few more strings and they are remaining to be translated, but we'll have 100% French translation by v0.5.0 stable.
