### ISSUE TITLE
Media output doesn't work

### ISSUE THREAD

**Issue by Vijorich** [vicolo-dev/chrono#209]
**Describe the bug**
Outputting music through media outputs it not only to the headphones but also to the phone's speakers

**To Reproduce**
1. Go to sound settings
2. Click on audio channel
3. Choose "media"
4. Wait for alarm
5. Phone speakers and headphones are playing in the same time

**Expected behavior**
If I choose media output, I wait to tha t only headphones will play alarm sound and I will not wakeup my neighbors

**Smartphone Information**
 - Device: Realme 6 pro
 - OS: Android 14 Horizon os
 - App version: 0.4.3

**Additional context**
Headphones are wireless, redmi buds 5 pro
Alarm logs:
![Screenshot_20240505-005733_Chrono.png](https://github.com/vicolo-dev/chrono/assets/88296320/86991780-c3ff-4744-8b4c-761e9e609a98)

**Comment by AhsanSarwar45** [comment]
That's strange since this should be handled by Android itself. I do remember once having this issue with another app and it got fixed by restarting the device. Can you try that in case you haven't already?

**Comment by Vijorich** [comment]
> That's strange since this should be handled by Android itself. I do remember once having this issue with another app and it got fixed by restarting the device. Can you try that in case you haven't already? 

Yeah, restarted, reinstalled and other re's already tried

**Comment by AhsanSarwar45** [comment]
I think that's because media output, quite literally, is not working. Its still using the alarm audio channel. To confirm, when you change media volume on your device, does that change the volume of the alarm when audio channel is set to media? (Quick tip, go to Settings -> Developer Options -> Turn on quick alarm button. This shows a button next to add alarm button to test alarms quickly)

**Comment by AhsanSarwar45** [comment]
This should be fixed in the [v0.5.0-beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta2) release. Let me know if there are any issues with it.
