### ISSUE TITLE
Option to open to a specific page of the app

### ISSUE THREAD

**Issue by Nowruz** [vicolo-dev/chrono#210]
Please add the option to open the app to a specific page, like the clock page instead of the alarm page. Or the the ability for the app to remember the last open page before closing.

**Comment by Warden20** [comment]
Simple clock has this. 
It would be great to be an intent. 
The simple clock works with this intent android.intent.action.SHOW_TIMERS

**Comment by AhsanSarwar45** [comment]
Thanks for the suggestion, this has been added in the v0.5.0-beta1 release. You can find it in Settings > General > Default Tab. Let me know if there are any issues.
