### ISSUE TITLE
Alarm STOPS music

### ISSUE THREAD

**Issue by atom-smasher** [vicolo-dev/chrono#212]
**Describe the bug**
When the alarm rings, any music app (eg MP3 player, streaming app) stops playing music. Even worse, any bluetooth controls that should (re)start the music don't work; the music-player app needs to be opened and playing music has to be manually re-started.

**Expected behavior**
Normal alarm behavior would be pausing the music during the alarm, then un-pausing (re-starting) the music when the alarm is turned off. Bluetooth control remains with the app that was previously playing music.

**To Reproduce**
1- Play music (eg RadioDroid, Rocket Player, Musicolet)
2- Have an alarm ring
3- Music stops. Bluetooth control is no longer connected to the app that was playing music.

**Screenshots**
N/A

**Smartphone Information**
 - Motorola Moto G8 Power (Resurrection Remix)
 - Android 10
 - App version 0.4.3 (F-droid)

**Additional context**
I'm used to alarm apps un-pausing the music after an alarm is finished. I should at least be able to re-start the music via bluetooth headphones or speaker controls. If the phone is packed in a bag, and I'm listening to music or a podcast via bluetooth headphones or speaker, I need to unpack the phone, unlock the phone, open the app, and re-start the music.

Thank you! Some bugs, but this is quickly becoming my favourite alarm & clock app!

**Comment by AhsanSarwar45** [comment]
Thanks for the report, this should be fixed in the [v0.5.0-beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta2) release. Let me know if there are any issues with it.

**Comment by atom-smasher** [comment]
Not yet tested with bluetooth, but otherwise it seems good. Thanks!
