### ISSUE TITLE
Chrono app assumes foreground after alarm is finished

### ISSUE THREAD

**Issue by atom-smasher** [vicolo-dev/chrono#213]
**Describe the bug**
Chrono app assumes foreground after alarm is finished.

**Expected behavior**
If Chrono is not in the foreground when the alarm rings, it should remain not in the foreground after the alarm is finished.

**To Reproduce**
1. Set an alarm.
2. Open another app in the foreground.
3. Turn off the display.
4. Wait for the alarm, and turn it off.
5. Unlock the phone, and Chrono is now in the foreground.

**Screenshots**
N/A

**Smartphone Information**
- Motorola Moto G8 Power (Resurrection Remix)
- Android 10
- App version 0.4.3 (F-droid)

**Additional context**
Thank you! Some bugs, but this is quickly becoming my favourite alarm & clock app!

**Comment by AhsanSarwar45** [comment]
Thanks for the report, this should be fixed in the [v0.5.0-beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta2) release. Let me know if there are any issues with it.
