### ISSUE TITLE
Time until next alarm

### ISSUE THREAD

**Issue by atom-smasher** [vicolo-dev/chrono#214]
**Is your feature request related to a problem? Please describe.**
Missing information

**Describe the solution you'd like**
When adding or enabling a new alarm, a message briefly appears, eg "Alarm will ring in less than 1 minute". What I'd like to see is a constant notification above the list of alarms indicating time until next alarm.

**Describe alternatives you've considered**
N/A

**Additional context**
Thank you! Some bugs, but this is quickly becoming my favourite alarm & clock app!

**Comment by sornay** [comment]
This feature would be very useful to me too. I hope it gets added soon

**Comment by AhsanSarwar45** [comment]
Hi, thanks for the suggestion. I've added this, but maybe a bit different from what you suggested. I didn't want it to take too much space, and also wanted it to offer a bit more functionality. So I have added it as part of the list filters.

![image](https://github.com/vicolo-dev/chrono/assets/41967492/0563e6a2-862a-4d24-88d7-09beed366d15)
It acts like any other filter, and clicking on it will show the next alarm itself, so you can disable it  quickly etc.

![image](https://github.com/vicolo-dev/chrono/assets/41967492/de042165-4231-4aed-aa3f-8d7a420c7844)

This is turned off by default but can be enabled by going to `Settings > Alarms > Filters > Show Next Alarm`. It will be available in the next release.

**Comment by AhsanSarwar45** [comment]
This should be available in [v0.5.2-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.2-beta1). Let me know if you face any issues.
