### ISSUE TITLE
Wakeup Check

### ISSUE THREAD

**Issue by Ensnare2** [vicolo-dev/chrono#219]
I'm always frustrated when I set my alarm and turn it off then go back to sleep.

In 2 minutes get a wakeup check where it does not go off unless I don't click I'm awake within the 2 minutes.

Setting a new alarm to go 5 minutes after.

**Comment by AhsanSarwar45** [comment]
Closing this in favor of #152, please continue the discussion there. Let me know if this is different and we can re-open this again.
