### ISSUE TITLE
Select audio file from internal storage

### ISSUE THREAD

**Issue by IM71** [vicolo-dev/chrono#220]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Please add a option that can select audio file from internal storage so that we can customize the sound of alarm, timer...etc.

Thank you

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by AhsanSarwar45** [comment]
Hi, You can already do so by going to settings > general > melodies. I should add a 'add' button on the melody select menu itself so people don't get confused in the future.
