### ISSUE TITLE
Analog clock support

### ISSUE THREAD

**Issue by CloneWith** [vicolo-dev/chrono#221]
**Description**
An analog clock could add an icy touch to the modern and simple interface.

**Solution**
Add an analog clock with smoothly spinning hands, and add a switch in the settings page or somewhere else.

**Comment by AhsanSarwar45** [comment]
Thanks for the request, I've added option to enable analog clock by going to Settings > Clock > Clock Type > Analog. Also added some customization settings, although currently, the second hand is not 'smooth',  but that is on the radar. You can test it in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1).
