### ISSUE TITLE
Multiple selection support

### ISSUE THREAD

**Issue by CloneWith** [vicolo-dev/chrono#222]
**Description**
With a lot of alarms or clocks, deleting them one by one is quite difficult and annoying. And filters won't work when I am deleting alarms from multiple tags.

**Solution**
Add a function to activate the multiple selection state by long pressing an item, or pressing a button at the top of the screen.
Then a checkbox appears beside each object in the list, allowing to batch delete / tag them or do anything else.

**Comment by AhsanSarwar45** [comment]
I'm closing this in favor of #186, please continue the discussion there.

**Comment by CloneWith** [comment]
> Although, can you elaborate what you mean by this?

This is not a bug. It's just a situation where I want to delete alarms, and when they don't seem to have the same tag. And adding support to multiple selections can make this easier.

I didn't explain it well. Anyway thanks for telling me that!
