### ISSUE TITLE
Alarm app can't open

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#242]
**Describe the bug**
when you add digital clock widgets  Alarm app can't open
**To Reproduce**
1. Go to 'add digital widgets'
2. Click on 'chrono app'
4. See error (can't open app)

**Expected behavior**

**Screenshots**

**Smartphone Information**
 - Device: []
 - OS: [e.g. Android 10]
 - App version [e.g. 0.5]

**Additional context**

**Comment by AhsanSarwar45** [comment]
Can you share more information? Your steps and explanation aren't clear at all. Maybe screenshots or recording will help.

**Comment by iBabu007** [comment]
Screen recording can't upload because it is >10mb.

**Comment by azeem-io** [comment]
Ok I understand. I'll look into this.

**Comment by AhsanSarwar45** [comment]
Ok I get it, I'll look into this.

**Comment by AhsanSarwar45** [comment]
This should be fixed in [v0.5.0-beta3](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta3). Let me know if you face any issues.
