### ISSUE TITLE
Improve dial to chose time / hour

### ISSUE THREAD

**Issue by th23x** [vicolo-dev/chrono#253]
**Is your feature request related to a problem? Please describe.**

The current "dial" option to chose the hour of an alarm puts the 24h of the day around a circle for easy access. 

However this results in midday/noon 12 to be at the bottom of the circle - counterintuitive to the normal watch. 

Additionally the uneven numbers are not directly visible - likely due to space on the screen. 

![Screenshot_20240518_072237_Chrono](https://github.com/vicolo-dev/chrono/assets/13735303/5fd88de6-f11a-49fe-a30e-fca8677aa1ee)

**Describe the solution you'd like**

Chamge to a double circle (inner an outer) with 12 positions / hours making them all visible at once and having them in the expected position eg 3 morning / 15 afternoon on the right hand side. 

![Screenshot_20240518_000209_Clock](https://github.com/vicolo-dev/chrono/assets/13735303/3ce19e31-0227-484f-a10d-0d80df6d689c)

**Describe alternatives you've considered**

Using another input method provided eg spinner, but it takes longer to chose. 

**Additional context**

n/a

**Comment by AhsanSarwar45** [comment]
Nice timing, this should be out in the [v0.5.0-beta2](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta2) release. Let me know if there are any issues with it.

**Comment by th23x** [comment]
Very cool, that was a quick solution - thanks a lot for your work. Awesome project :-)
