### ISSUE TITLE
Stopwatch: Last lap missing after pushing stop

### ISSUE THREAD

**Issue by th23x** [vicolo-dev/chrono#255]
Sorry for the couple bugs/requests lately, but startin to use your cool app, I came across some :-) 

**Describe the bug**

Last lap / remaining time not visible after stopping the stop watch - only previous laps are shown in the list. 

**To Reproduce**

1. Start stop watch
2. Time a few laps
4. Press stop 
5. See error - last lap/remaining time not shown

**Expected behavior**

Stopping should show all laps summing up to completed time. 

**Screenshots**

https://github.com/vicolo-dev/chrono/assets/13735303/9a8bce0f-5717-4978-ae18-6d39197559a4

**Smartphone Information**
 - Device: Samsung S10e
 - Android 12
 - App version: 0.50-beta

**Additional context**
n/a

**Comment by th23x** [comment]
Maybe two more thoughts on this:

1) Clicking Lap button after Pause shows the missing lap - my expectation was, that the Pause equals Stop and thus would also create the final lap

2) If Pause should not equal Stop would expect a dedicated Stop button, creating the final lap

**Comment by AhsanSarwar45** [comment]
I think the way other apps handle this to always show the current lap in the list too, so laps always add up to total time, whether paused or running. Chrono only shows finished laps.

**Comment by AhsanSarwar45** [comment]
I have updated it so it also shows the current lap at all times, which I think is the best behavior. It should be available in  [v0.5.2-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.2-beta1). Let me know if you face any issues.

**Comment by th23x** [comment]
Great - looks good in the newest release 👍
