### ISSUE TITLE
Add an option to invert the order of the rapid alarm settings buttons

### ISSUE THREAD

**Issue by STVGecko** [vicolo-dev/chrono#259]
**Is your feature request related to a problem? Please describe.**
I often accidentally click on the delete button of the rapid alarm settings buttons

**Describe the solution you'd like**
Add an option to invert the order of the rapid alarm settings buttons

See first photo to -> second photo

![1000008307](https://github.com/vicolo-dev/chrono/assets/71868745/3906ccf0-6454-46ad-8df3-2c51045c5ab1)

![21000008307](https://github.com/vicolo-dev/chrono/assets/71868745/7d977f96-d8a1-4b1e-a797-3133c53b54e6)

**Comment by AhsanSarwar45** [comment]
Thanks, sounds like a good idea.

**Comment by AhsanSarwar45** [comment]
This should be added in [v0.5.0-beta3](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta3). Let me know if you face any issues.
