### ISSUE TITLE
Timer setting - spinner wheels hardly readable

### ISSUE THREAD

**Issue by th23x** [vicolo-dev/chrono#263]
**Describe the bug**

See screenshot below in dark mode, with amoled option on. 

![Screenshot_20240519_072154_Chrono](https://github.com/vicolo-dev/chrono/assets/13735303/465b1a9f-ad3b-4397-96ab-dfae320a1da7)

**To Reproduce**

1. Set new time
2. Chose spinner for selecting time
3. See error

**Expected behavior**

White / grey text color readable on dark background 

**Screenshots**

See above

**Smartphone Information**
 - Device: Samsung S10e
 - OS: Android 12
 - App version 0.50-beta2

**Additional context**

If I remember correctly it looked different before

**Comment by AhsanSarwar45** [comment]
Thanks for the report, this should be fixed in [v0.5.0-beta3](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta3). Let me know if you face any issues.

**Comment by th23x** [comment]
Looks good, well readable now :-) Thanks!
