### ISSUE TITLE
Timer notification - Add remaining time to notification title 

### ISSUE THREAD

**Issue by th23x** [vicolo-dev/chrono#264]
**Is your feature request related to a problem? Please describe.**

With default options the notification for a timer only shows the timer title and the progress bar. It's hard to know how much time is remaining exactly. 

**Describe the solution you'd like**

Add the remaining time to the notification title - there is enough space left and the notification gets anyhow updated for the progress update.

![Screenshot_20240519_065710_Chrono](https://github.com/vicolo-dev/chrono/assets/13735303/96270de8-0223-4bd7-9b6a-4bee4f277a84)

**Describe alternatives you've considered**

Open the notification to see details, but its additional effort for every look... 

**Additional context**

n/a

Once more thanks for your efforts - I really like the app offering many things together while being customizable :-)

**Comment by AhsanSarwar45** [comment]
Thanks for the suggestion. I think this really improves usability so I have added it in [v0.5.2-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.2-beta1). Let me know if you face any issues.

**Comment by th23x** [comment]
Thanks a lot for the enhancement - work great in the latest update 👍
