### ISSUE TITLE
Timer dismiss action type is mapped incorrectly

### ISSUE THREAD

**Issue by aronovgj** [vicolo-dev/chrono#285]
Setting dismiss action type to "slider" shows area buttons when timer is ringing. 
Correspondigly, "area buttons" sets buttons and "buttons" sets slider

**Comment by AhsanSarwar45** [comment]
Thanks for the report, this should be fixed in [v0.5.2-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.2-beta1). Let me know if you face any issues.
