### ISSUE TITLE
New "alarm and reminder" background functionality

### ISSUE THREAD

**Issue by STVGecko** [vicolo-dev/chrono#286]
**Is your feature request related to a problem? Please describe.**

I don't know why, alarms often don't go off, usually when they're close by.

**Describe the solution you'd like**
On several other alarm applications, it is possible to define an application as "alarm and reminder" in "special access" (see photo below).

It says:

"Alarms and reminders

Allow this application to set alarms and schedule actions at certain times. 
It will then run in the background, which can 
battery. 

If authorisation is disabled, existing alarms and events 
alarms and events programmed by the 
the app will not work."

![1000008424](https://github.com/vicolo-dev/chrono/assets/71868745/be69bfa0-10da-44f8-9554-be29b329cbc2)

Off-topic: do you know how to reduce the size of photos on github for this type of issues ?

**Comment by aronovgj** [comment]
Duplicate 
https://github.com/vicolo-dev/chrono/issues/183

**Comment by AhsanSarwar45** [comment]
Thanks, please continue this conversation in #183.
