### ISSUE TITLE
Next alarm time in Widget

### ISSUE THREAD

**Issue by Joerg123** [vicolo-dev/chrono#287]
This is a very nice app, thanks a lot for providing it.
There is just one feature missing for me. The widget should show the time of the next alarm.
This information could be fitted below the date, commencing e.g. with an alarm clock symbol, followed by the weekday (when not today) and the time of the alarm.

Best regards
Jörg

**Comment by th23x** [comment]
This might be a duplicate to the second part of my suggested enhancement in #244

Glad to see other users having similar ideas :-)

**Comment by AhsanSarwar45** [comment]
Thanks for the suggestion. I'll close this in favor of #244, please carry the conversation there.
