### ISSUE TITLE
Changing add length for timer has no effect 

### ISSUE THREAD

**Issue by aronovgj** [vicolo-dev/chrono#288]
Error path:
- Set default add length for timer to 2 minutes
- create timer and let it ring
- tap add length 2 minutes

Actual behavior:
- 1 minute of length is added to timer

Expected:
- 2 minutes of length should be added to timer

**Comment by AhsanSarwar45** [comment]
Thanks for the bug report. This should be fixed in [v0.5.2-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.2-beta1). Let me know if you face any issues.
