### ISSUE TITLE
Add functions when the application button is held down

### ISSUE THREAD

**Issue by STVGecko** [vicolo-dev/chrono#291]
**Describe the solution you'd like**
Add functions when the application button is held down, as https://f-droid.org/packages/com.best.deskclock/

-New alarme/ring
-New timer
-Start the stopwatch

![Screenshot_20240527_075938_One UI Home](https://github.com/vicolo-dev/chrono/assets/71868745/9f8a0973-5fbe-412b-b9b4-1afb5ace8214)

-screen saver (a mode that puts the screen to sleep with the time displayed)

![Screenshot_20240607_100402_Clock](https://github.com/vicolo-dev/chrono/assets/71868745/7c89edff-039d-4c27-bf4b-1e3a80ab985b)

**Comment by AhsanSarwar45** [comment]
I've added some shortcuts, refer to this https://github.com/vicolo-dev/chrono/issues/322#issuecomment-2365239238.
