### ISSUE TITLE
No future date even after setting it up.

### ISSUE THREAD

**Issue by syaifurrizal** [vicolo-dev/chrono#294]
**Alarm failed to read date range**

After set the date range for each alarm, save it it will show enable/disable toggle. But after I close and reopen the app, it said "no future date" and the enable/disable toggle gone and become delete icon.

**To Reproduce**

1. Create an alarm 
2. Set "date range".
3. Set "delete after finishing"
4. Save it.
5. Close the app completely.
6. Open the app again.
7. From the alarm list it will show "no future date" and the enable/disable toggle become delete icon.

**Expected behavior**

- Below the alarm should be a sunrise icon with info the date range after reopen the app.
- The enable/disable toggle still present after reopen the app.

**Screenshots**

Right after set the alarm:

![Screenshot_2024-06-17-12-51-29-335_com.vicolo.chrono.jpg](https://github.com/vicolo-dev/chrono/assets/12688026/292baa18-551b-4e14-b792-71d2a13b1acf)

After reopen:

![Screenshot_2024-06-17-12-50-13-450_com.vicolo.chrono.jpg](https://github.com/vicolo-dev/chrono/assets/12688026/81e3b078-8a7c-4ebc-b3de-2edd4b0fb738)

**Smartphone Information**

 - Device: [Xiaomi Redmi 10]
 - OS: [Android 13]
 - App version [0.51]

**Additional context**

- All necessary settings related to Xiaomi battery optimization already disabled.
- Pause the app if not used also disabled.

**Comment by th23x** [comment]
Cam confirm this behavior, even without activating the "delete after finishing" option it doesn't have the alarms active after restart of the app.

**Comment by syaifurrizal** [comment]
Yes, it works fine. Yesterday I was worried because the date range wasn't shown.

Thank you.

**Comment by th23x** [comment]
Sorry, maybe a misunderstanding...

I meant I can confirm the bug you reported. It should have shown the alarms as active (switch), but does not.

So I would not close thia, but keep your report open!?

**Comment by AhsanSarwar45** [comment]
Yes I am able to reproduce this too.

**Comment by AhsanSarwar45** [comment]
This should be fixed in [v0.5.2-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.2-beta1). Let me know if you face any issues.
