### ISSUE TITLE
Add widgets

### ISSUE THREAD

**Issue by ViktorKahu** [vicolo-dev/chrono#3]
Please add homescreen widgets for:

A) showing the clock; and
B) showing/setting the alarm

The more options/abilities to customize the better. A personal wish is to have a vertical clock with seconds, and a widget background transparency option, if implemented.

Eg:

Date
HH
MM
SS

Thanks :)

**Comment by AhsanSarwar45** [comment]
Yup, this was something I have been thinking of doing for some time now. Will let you know when I start working on it 😃

**Comment by iBabu007** [comment]
![1155511_featured-1371805162](https://github.com/vicolo-dev/chrono/assets/65340361/c6c8faf5-b0dc-4c44-b22d-a4b1c405a5bd)

![google-material-you-widgets-4011872345](https://github.com/vicolo-dev/chrono/assets/65340361/ec2168bc-d5a6-4abe-84e6-359ab8906cb5)

**Comment by iBabu007** [comment]
Hey, developer please add atleast a Simple widget first then you add more or improved it.

**Comment by inson1** [comment]
I would like same widget as SMT clock

**Comment by ViktorKahu** [comment]
I'm guessing this isn't happening then.

**Comment by inson1** [comment]
@ViktorKahu its only temporarily paused, you dont have to close right away

**Comment by AhsanSarwar45** [comment]
Reopened this because I want to start working on this.

**Comment by th23x** [comment]
Any chance to "sponsor" the widget development specifically?

I really love the app, but lack a simple widget showing "time", second line "weekday, day month" on transparent background and on click opening the alarm setting.

Happy to contribute some Euros to support :-)

**Comment by potatocinna** [comment]
I think the best you can do is support them through **[their Patreon](https://www.patreon.com/vicolo)** and show them you care :+1: Have a lovely day ;)

**Comment by AhsanSarwar45** [comment]
> Any chance to "sponsor" the widget development specifically?
> 
> I really love the app, but lack a simple widget showing "time", second line "weekday, day month" on transparent background and on click opening the alarm setting.
> 
> Happy to contribute some Euros to support :-)

Thanks for your consideration! I did do some initial work on widget support a while back. I am hoping I can get it done for the next major release (v0.5.0). Initial version will atleast add the default android digital and analogue clock widgets. Later versions will add more customization, as well as widgets for setting alarms and timers directly. This will take some time to do correctly, as interfacing with widgets from Flutter isn't straightforward. Of course any donations would help me put more time into development so they will get done quicker. And yes, like @potatocinna mentioned, I currently only have a Patreon. Would have preferred something like Liberapay or Buy me a coffee, but sadly no other option is available for my country.

**Comment by th23x** [comment]
"I currently only have a Patreon"

Thanks for the quick reply. Happy to support via Patreon, but looking at the fees and models offered, I prefer to pay a higher one time sum to get more money to you...

Anyhow, great work done so far!

**Comment by AhsanSarwar45** [comment]
> Thanks for the quick reply. Happy to support via Patreon, but looking at the fees and models offered, I prefer to pay a higher one time sum to get more money to you...
> 

If you want, you can create a custom pledge by clicking 'Upgrade', scrolling down to the bottom, choose custom pledge, and just cancel pledge after being charged.

> Anyhow, great work done so far! 

And thanks for the kind words :)

**Comment by th23x** [comment]
> create a custom pledge ... and just cancel pledge after being charged

Great, thanks for the hint - that worked :-) Sorry for the "spam" in this issue, but hope it helps. Back to the widgets ;-)

**Comment by AhsanSarwar45** [comment]
Hi everyone, check out the [v0.5.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.5.0-beta1), which has widgets support (finally)! There are only 2 widgets for now (analog and digital clock), although I have added customization options for digital clock widget. More widgets and customization options will come in later updates. Let me know of any issues and feedback.

**Comment by AhsanSarwar45** [comment]
Closing this for now, please create new issues for any bugs or widget/feature request.
