### ISSUE TITLE
Redued app size.

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#30]
Please if possible then reduced it size,
it take almost 30 mb (after install).
If possible then reduced it size around 10 mb like pre installed size.

![Screenshot_20231216-164141](https://github.com/vicolo-dev/chrono/assets/65340361/24e0ba77-943a-45ca-9230-5ad98d52ab29)

**Comment by kaanelloed** [comment]
This is not something the developer can do, as the size of the installed application is always much larger than the size of the apk file.

**Comment by iBabu007** [comment]
Then it is not possible to reduced it size.

**Comment by azeem-io** [comment]
We have already reduced the app size to a large extent. Further optimizations might be possible but the gains wont be much noticeable, unless flutter does this on their end. Closing this issue for now.
