### ISSUE TITLE
No area buttons when timer goes off  (0.5.2 beta 1)

### ISSUE THREAD

**Issue by aronovgj** [vicolo-dev/chrono#304]
Error path:
- Set a timer
- turn off screen
- observe

Expected:
- Screen with area buttons
- No lock screen 

Actual:
- Lock screen stays on
- Notification is shown that an alarm is active

**Comment by AhsanSarwar45** [comment]
Have you provided permission for app to appear over lock screen?

**Comment by aronovgj** [comment]
You are right, didn't see that. Though I updated the app and the permission seems to have reset. If you think the fact that it reset is not an issue, we can close this.

**Comment by AhsanSarwar45** [comment]
It shouldnt have reset, but I'm guessing it might have something to do with me adding another notification channel. We can close this for now but if we continue seeing it being reset after future updates, we can create a new issue for that.
