### ISSUE TITLE
"Skip Next Alarm" is not entirely skipping next alarm

### ISSUE THREAD

**Issue by atom-smasher** [vicolo-dev/chrono#306]
**Describe the bug**
When I "Skip Next Alarm", the alarm still seems visible to the system.

**To Reproduce**
1. Set an alarm
2. "Skip Next Alarm"
3. View the lockscreen that shows the next alarm time, and see the skipped alarm's time

**Expected behavior**
After "Skip[ping] Next Alarm", that skipped alarm should not be known to the system.

**Screenshots**
1/2 -

![Screenshot_alarm-1](https://github.com/vicolo-dev/chrono/assets/8199959/80f63bf6-33fa-4dad-8858-d7f015ebe213)

2/2 -

![Screenshot_alarm-2](https://github.com/vicolo-dev/chrono/assets/8199959/5b93ead2-02ed-41c3-9ae8-85a30d17edbe)

**Smartphone Information**
 - Motorola Moto G8 Power (Resurrection Remix)
 - Android 10
App version: 0.5.1

**Additional context**
N/A

**Comment by AhsanSarwar45** [comment]
This should be fixed in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1).

**Comment by atom-smasher** [comment]
Working correctly from the app. I'll test later by skipping an alarm from the notification. Thanks.
