### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [vicolo-dev/chrono#307]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7223804781#L1121

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/44477f0a85e673c570d2a979da894fa2e199141b

difflog: 
[chr251.log.7z.zip](https://github.com/user-attachments/files/16051686/chr251.log.7z.zip)
 (remove `.ZIP` from name)

**Comment by AhsanSarwar45** [comment]
Can we try again? I have uploaded the gradle-wrapper file that might fix the issue. I have also changed the flutter version to `3.22.2`. Should I open a merge request on Gitlab?

**Comment by AhsanSarwar45** [comment]
Thanks a lot. I would like to keep publishing the releases with `beta` tag.
