### ISSUE TITLE
[Feature] Add a field for hex code in the color picker

### ISSUE THREAD

**Issue by potatocinna** [vicolo-dev/chrono#31]
Heyy! 
The title says it all, would it be possible to add one in the appearance settings?
Thanks ٩(ˊᗜˋ*)و ♡

![Screenshot_20231216-150516_Chrono](https://github.com/vicolo-dev/chrono/assets/122670684/e4f8189f-4baa-4f50-ad58-d8e2281333ed)

**Comment by AhsanSarwar45** [comment]
Hi, added this in 0.2.10. Let me know if you face any issues :)
