### ISSUE TITLE
Palestine, not "Palestinian territory"

### ISSUE THREAD

**Issue by GamzeeRakoon** [vicolo-dev/chrono#315]
**Describe the bug**
Palestine is a state recognized by the majority of nations around the globe with a 145 out of 193 nations in the UN giving recognition.

calling the state of palestine, "territory" only adds to the erasure of the palestinian people by implying they are part of israel, when they have the right to self determination like every nation

**To Reproduce**
1. Go to 'clock'
2. Click on '+'
3. Search 'palestine'
4. See nothing show up, only when searching "palestinian territory" will it show.

**Expected behavior**
Palestine shows up when searched for.

**Screenshots**
![Screenshot_20240718_125832_Chrono](https://github.com/user-attachments/assets/c20c81dc-6c95-4b59-8375-88baa441cfaf)

**Smartphone Information**
 - Device: n/a
 - OS: n/a
 - App version: 0.5.1

**Comment by AhsanSarwar45** [comment]
Hi, thanks for pointing this, I will fix it.

**Comment by AhsanSarwar45** [comment]
Should be fixed in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1).
