### ISSUE TITLE
Select and act on alarms without filters

### ISSUE THREAD

**Issue by mentonin** [vicolo-dev/chrono#319]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to apply an action (like delete or skip) to multiple alarms at once, but there isn't a good filter to apply to them.

**Describe the solution you'd like**
I wish I could manually select a list of alarms in the main screen. The multi-selection could be started by long pressing on an alarm or by an item in the quick menu. Tapping an alarm when in multi-select mode would toggle it being selected. A button to invert selection on the top.

**Comment by azeem-io** [comment]
Thanks for the request, I think this is the same as #186 so lets continue the discussion there.
