### ISSUE TITLE
Black system navigation bar

### ISSUE THREAD

**Issue by PhilippKosarev** [vicolo-dev/chrono#321]
**Describe the bug**
The system's navigation bar is a different colour from that of the app.

**Expected behavior**
The system's navigation bar should be the same as the app's, accounting for the selected style.

**Screenshots**
![Chrono00981](https://github.com/user-attachments/assets/a81371ec-85d2-4c25-ae4d-55615f30d2f9)

**Smartphone Information**
 - Device: Samsung A25 5G
 - OS: Android 14
 - App version 0.5.1

**Additional context**
Thank you for the best clock app :)

**Comment by AhsanSarwar45** [comment]
Thanks for the report, I've fixed it, should be out in the next release.

**Comment by AhsanSarwar45** [comment]
This should be fixed in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). If you face any issues, feel free to reopen this issue.
