### ISSUE TITLE
shortcut to access tabs

### ISSUE THREAD

**Issue by LeonelRFF** [vicolo-dev/chrono#322]
**Is your feature request related to a problem? Please describe.**
Hello, In my phone's default clock.  Currently, it only has the alarm function, as seen in the image.  (However, it does not have the function of disabling alarms through tasks 🥲).  Since I use multiple timers to monitor various activities, 
![Screenshot_2024-08-20-19-45-42-62_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/a6a8d769-c283-4dbb-aed9-7ee49d1bd3c7)
![Screenshot_2024-08-20-19-45-50-15_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/bc190cef-e7a8-4196-ac86-ef5d53afe37c)

**Describe the solution you'd like**
it would be useful to add a shortcut to the timer tab, or even all tabs, having quick access to the preset timers I have would be very beneficial.
![Screenshot_2024-08-20-19-45-59-99_b783bf344239542886fee7b48fa4b892](https://github.com/user-attachments/assets/fe4c74a7-572d-490a-91af-1216fdd5025d)

As you can see in the image it does not have any shortcut to add

**Comment by AhsanSarwar45** [comment]
Hi, thanos for the request, I've added this, it will be out in the next release 0.6.0

**Comment by AhsanSarwar45** [comment]
This should be out in [0.6.0-beta1](https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta1). Currently, only two shortcuts have been added (alarm and timer). I'm yet to make some design decisions about other shortcuts (like presets etc), but they are on the radar too. Consider creating a new issue if you have any feedback or face any issues.

**Comment by LeonelRFF** [comment]
Hello, I installed the beta version and the shortcuts work, although for personal and practical tastes I go to that tab and press one of the many timers that I have preset 😁⏲️ another thing I don't know if the error still continues that when starting a timer and turning off the screen it doesn't sound, at least it happened to me when trying to test it, it didn't sound, you have to enter the app for it to work.
