### ISSUE TITLE
Idea : add an option to disable the ringing when solving the challenges

### ISSUE THREAD

**Issue by MarvinZhong** [vicolo-dev/chrono#325]
**Is your feature request related to a problem? Please describe.**
The ting sounds sometimes made hard to focus and anxious when solving the challenges

**Describe the solution you'd like**
Add a setting option to disable the sound when solving the challenges

**Describe alternatives you've considered**

**Additional context**
Maybe take a look at Alarmy app

**Comment by AhsanSarwar45** [comment]
Hi, I think this is the same as #108 so lets continue the discussion there.
