### ISSUE TITLE
gradle wrapper missing

### ISSUE THREAD

**Issue by IzzySoft** [vicolo-dev/chrono#326]
Your project lacks a gradle wrapper. Most likely you have that locally but forgot to commit it to the repo. Or you maintain your local gradle version manually. It would be nice if you could set up a gradle wrapper to make it easier for others to build – e.g. for [Reproducible Builds](https://reproducible-builds.org/) (see e.g. [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)). If you don't know why, it should be rather easy, see e.g. the [Gradle Wrapper Reference](https://docs.gradle.org/current/userguide/gradle_wrapper.html):

    $ gradle wrapper

then add, commit and push – that should be it (will add the files based on your local gradle version).

Thanks in advance!

**Comment by AhsanSarwar45** [comment]
Wouldn't that be this file https://github.com/vicolo-dev/chrono/blob/abc199dd25aaea2ad7d0ab1dbd9a7c1577ebbfdf/android/gradle/wrapper/gradle-wrapper.properties, or is this something different?

**Comment by IzzySoft** [comment]
There should be an accompanying JAR file. Results should look something [like this](https://github.com/Armand31/Dividoc/tree/main/gradle/wrapper) (just picking that as I had it in an open tag, not because it's "special" :wink:)

**Comment by AhsanSarwar45** [comment]
I've added the jar file in the latest release. Let me know if it fixes the issue.

**Comment by IzzySoft** [comment]
Apologies for the late response, I was on vacation…

The newer releases are marked pre-release, so they luckily were not picked up automatically (as the recipe was not yet adjusted here, that probably would have gone wrong). I've just tried manually with the latest Beta – and it works perfectly, thanks! Not only is the new wrapper JAR found automatically, but the APK builds reproducible, too. So all fine – and all prepared for the next (not pre-) release, thanks!

At your convenience, feel free to close this issue as solved now – or leave it open until the next release was built RB on our end here.
