### ISSUE TITLE
Timer doesn't show minutes

### ISSUE THREAD

**Issue by PennyJim** [vicolo-dev/chrono#343]
**Describe the bug**
A timer with the time left of 1:00:01 to 1:00:59 will simply not display the 00 of minutes.

**To Reproduce**
1. Start an hour timer
2. Add a minute
3. See it *look* like there's only two minutes left.

**Expected behavior**
when there's any non-zero digit of hours left, it should display minutes.

**Screenshots**
![Screenshot_20240922-174806.png](https://github.com/user-attachments/assets/072942b8-631e-42f2-823d-6fd860665933)

(You can see the ring reflects the fact that this is actually an hour timer.

**Smartphone Information**
 - Device: Motorola Edge Plus 2023
 - OS: Android 14 (U1TRS34.8-30-18-2)
 - App version: 6.0 beta 1

**Additional context**
The screenshot was taken on the latest release (and version on fdroid), but I tried the beta and confirmed it still does it before reporting.

**Comment by AhsanSarwar45** [comment]
Thanks, fixed this. Will be out in `0.6.0-beta2`
