### ISSUE TITLE
Alarms persistent through manual deletion, reinstallation, clearing of storage/cache and restore to defaults

### ISSUE THREAD

**Issue by jakegb** [vicolo-dev/chrono#350]
ISSUE DESCRIPTION:
Alarms and other data (but not permissions or error logs) persistent through 
- uninstallation and reinstallation of app.
- clearing of storage/cache through android settings app.
- restoring of defaults through app.
- individual deletion of alarms in app
Additionally, combinations of the above were tried along side restarting between steps.

FURTHER DESCRIPTION:
After most recent update 0.6.0-beta1 I began experiencing the same bug and error code as described in issue#346 that being "Error decoding string: FormatException..." 
Thought it might be due to version conflict/update shenanigans with data formatting, thus decided to uninstalled and reinstalled app. 
After reinstallation bug was still present and so were all pervious alarms.
still operating under the assumption that the issue layed with my data rather than the app, I tried clearing both storage and cache of the app through my vendors setting app, using the 'restore to default' option in Chrono's settings menu and manually deleting alarms to no avail.
I tried combinations of the above as well as restarting between steps however the alarms remained.

HARDWARE, VERSION ECT:
Model: google pixel 8 version MP1.0
Android version: 14 build AP2A.240905.003
Chrono version: F-Droid 0.6.0-beta1

FURTHER INFO RELATING TO ISSUE#346 BUG:
Error logs (unfortunately only of the my latest install of the app)
[chrono_logs_2024-10-08T17_03_27.txt](https://github.com/user-attachments/files/17289254/chrono_logs_2024-10-08T17_03_27.txt)
Backup export
[chrono_backup_2024-10-08T18_05_08.json](https://github.com/user-attachments/files/17289265/chrono_backup_2024-10-08T18_05_08.json)

P.S.
Thanks for making and maintaining this app :)

**Comment by AhsanSarwar45** [comment]
I think that was caused by automatic backup on newer android versions. I have disabled that now in https://github.com/vicolo-dev/chrono/releases/tag/v0.6.0-beta2, if that was your case too, this will fix it. Let me know if works.

**Comment by jakegb** [comment]
Yep that's done it. Uninstalled and reinstalled and all alarms were gone. 
also the error message from issue #346 has gone as well.
Thanks

**Comment by AhsanSarwar45** [comment]
Good to hear :), although the format error might still resurface, so let me know if that happens. It was probably being caused by the background service, which I have disabled by default in this version.
