### ISSUE TITLE
Add option to disable/enable snooze for alarms

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#36]
Please add a on/off button inside snoozed option.

**Comment by AhsanSarwar45** [comment]
Hi, can you elaborate what you mean?

**Comment by iBabu007** [comment]
![Screenshot_20231218-104734](https://github.com/vicolo-dev/chrono/assets/65340361/074a8a9b-58ec-4520-b986-7806f7ac4d17)
