### ISSUE TITLE
Alarm keeps playing despite dismissing via notification popup

### ISSUE THREAD

**Issue by KeronCyst** [vicolo-dev/chrono#360]
**Describe the bug**
The alarm tone keeps playing as if you never dismissed an active alarm, even if you did—if you dismiss it via the notification popup from the top of the screen if you were already using your phone at the time of the alarm tone.

**To Reproduce**
1. On Android 12, schedule a one-time alarm
2. Be using the phone with the screen on at the time of the alarm, and then touch "Dismiss" in the popup that descends from the top of the screen
3. Only the notification is dismissed; the alarm keeps playing as if you did nothing, even though Chrono shows it as being turned off in its overview of alarms.

**Expected behavior**
The sound should stop.

**Smartphone Information**
 - Device: Samsung S21 FE 5G
 - OS: Android 12
 - App version: 0.6.0-beta1
 
**Additional details**
The only way I could get the alarm tone to stop was to force-quit the app.

**Comment by Cris-Edmundson** [comment]
Having the same issue on: 
Android 14
Device: Asus Zenphone 10
Same app version: 0.6.0-beta1

Hope this helps :)

**Comment by AhsanSarwar45** [comment]
I think this is the same as #323, let's continue the discussion there.
