### ISSUE TITLE
Improved it's notification panel UI

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#38]
Please improved it's notification panel UI design. Now it look like notification form another app.

![Screenshot_20231216-213411](https://github.com/vicolo-dev/chrono/assets/65340361/4750159e-0a49-4d1f-8b24-22dbb2257b25)

**Comment by AhsanSarwar45** [comment]
This style is defined by your system, not the app. So all apps will have the same notification style. Closing this for now. Feel free to open again if you feel otherwise.
