### ISSUE TITLE
REQ Allow alarm audio to be routed to media output

### ISSUE THREAD

**Issue by sanctimoniousape** [vicolo-dev/chrono#44]
I sleep with headphones (I have both wired and Bluetooth, depending upon how concerned I am with conserving battery power) to block out the world - mainly the neighbors, and my spouse who prefers to sleep with the TV sound on.  I would prefer the alarm played through the headphones instead of the speaker for those times I don't want to wake my spouse.  Please add this option if possible, thanks!

**Comment by AhsanSarwar45** [comment]
Hi, this should be available in the latest release (0.2.10). 
When creating an alarm or timer, you can go to `Customize > Sound and Vibration > Audio Channel`.
To set a default for all alarms, go to `Settings > Alarm > Default Settings > Sound and Vibration > Audio Channel`.
Let me know if you find any bugs 😄.

**Comment by EnderDragonEP** [comment]
The volume won't play above certain percentage (about 30%) when using this feature. I'm on Android 13.
