### ISSUE TITLE
Long press swipe(left/right)

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#5]
Hi, dev your app is toooo good..

Please add long pess swipe(left/right) for delete or duplicate.

Normal swipe action (left/right) use for tab change (alarm to clock... etc)

**Comment by AhsanSarwar45** [comment]
Hmm, swipe to change screens is a good idea. But I'll have to see what the best way to accommodate the swiping feature is. Currently long-press is used for reordering, which might interfere with the swipe, but I guess reordering isn't a particularly common use case, so maybe moving that to a different action will be best.

And glad to see you like the app 😄

**Comment by AhsanSarwar45** [comment]
This is available now by going to Settings > General > Swipe Action and choosing tab switch.
