### ISSUE TITLE
[Bug] Alarm doesn't save the parameters when not scheduled 

### ISSUE THREAD

**Issue by potatocinna** [vicolo-dev/chrono#54]
Heyaa!

Found this bug where when I make changes on an alarm and it's not scheduled it doesn't save my settings :c  
Here's a [quick video](https://youtube.com/shorts/atYSS30bv-U) (couldn't upload it on git  because too large sorry 🙏) for visual explanation! If you need info on my device or anything I'll try to be reactive (˶˃ ᵕ ˂˶)

I love the hexcode feature btw, thank you for the quick updates <3

**Comment by AhsanSarwar45** [comment]
Hi, thanks for the detailed video! This should be fixed in the next update. Will let you know when that drops.
