### ISSUE TITLE
Long ringtone file name didn't get cut off

### ISSUE THREAD

**Issue by leongjs98** [vicolo-dev/chrono#6]
In "Sound and Vibration | Melody", when customizing an alarm, if the custom ringtone has a long name, it will go off screen. This makes the users not able to click the play button.

Suggestion: the long name gets cut off with "..." and the play button still shows.

![Screenshot_20231215-200552_Trebuchet](https://github.com/vicolo-dev/chrono/assets/86957033/cdba1ee8-45d0-42bf-8a04-4461706489df)

**Comment by AhsanSarwar45** [comment]
Thank you, fixed it. Will be live in 0.2.8

**Comment by leongjs98** [comment]
Thank you, I like the functionalities of the app offers, not to mention the slick style.

I will mark this as completed.

**Comment by AhsanSarwar45** [comment]
@leongjs98 The update is out now. Feel free to reopen the issue in case you still encounter this.
