### ISSUE TITLE
Notification and snooze messages don't use the 24h format

### ISSUE THREAD

**Issue by kaanelloed** [vicolo-dev/chrono#65]
**Describe the bug**
Notification and snooze message don't use the 24h format.

**To Reproduce**
1. Set Time Format to 24 hours
2. Create an alarm
3. Snooze

**Expected behavior**
Notification and snooze message using the 24h format.

**Screenshots**
<img src="https://github.com/vicolo-dev/chrono/assets/11068249/4e1c3590-7e02-4192-a266-35128f241f3d" width=40% height=40%> <img src="https://github.com/vicolo-dev/chrono/assets/11068249/423a8faf-658c-4ecc-86f1-24380deeb175" width=40% height=40%>

**Smartphone Information**
 - Device: Google Pixel 5
 - OS: Android 14
 - App version 0.2.10

**Comment by AhsanSarwar45** [comment]
Thanks for the report, this should be fixed in the next version.
