### ISSUE TITLE
Dismiss snoozed alarm

### ISSUE THREAD

**Issue by kaanelloed** [vicolo-dev/chrono#66]
**Is your feature request related to a problem? Please describe.**
We need a way to manually dismiss a snoozed alarm manually, especially if prevent disabling while snoozed if activate.

**Describe the solution you'd like**
A button to dismiss or a notification that stay while the alarm is snoozed

**Comment by AhsanSarwar45** [comment]
Thanks, I think the best way would be to replace the disable switch with a dismiss button in such cases.
