### ISSUE TITLE
non-free library

### ISSUE THREAD

**Issue by IzzySoft** [vicolo-dev/chrono#68]
Having updated its definitions, my library scanner reports your app includes the [flutter-boot-listener](https://github.com/AhsanSarwar45/flutter_boot_receiver) library, which is considered non-free/proprietary as it has no license declared. So with the next sync, my repo will show that as AntiFeature for your app (with a proper note, for transparency). Should you have applied for inclusion with F-Droid.org, this will be a show-stopper, though, as F-Droid doesn't permit non-free components.

Just thought to let you know; maybe you can find a good replacement (with development of that Flutter module seemingly stopped a year ago, I have no idea how likely it is a license will finally be applied there; their license file just lists this as a "to do").

**Comment by AhsanSarwar45** [comment]
That library was written by me lol. Wrote it hastily last year, forgot to add a license 💀. Added one now though (GPL 3.0) 😁.

**Comment by IzzySoft** [comment]
Now, that of course solves this issue in the most easy way :rofl: *updates library definitions* nice. *removes AntiFeatures again* Yeah! :partying_face: Thanks!
