### ISSUE TITLE
Add the option to open chronos from the system clock

### ISSUE THREAD

**Issue by Warden20** [vicolo-dev/chrono#84]
**Is your feature request related to a problem? Please describe.*
With other alarm or clock apps I can smash on the clock in the notification area or any other system clock and it presents the options of which clock to open. But this app does not appear as an option. Why does this happen? And is there a possibility to fix it?

**Describe the solution you'd like**
Click in the clock and be able to open chronos

**Additional context**
Simple  clock from 
https://github.com/SimpleMobileTools/Simple-Clock has this option

**Comment by AhsanSarwar45** [comment]
Hi, Can you tell what device and android version did you use where SimpleClock is openable from system clock? I have tried android 12 (MIUI)  and 13 (XOS) but it doesn't appear to work.

**Comment by AhsanSarwar45** [comment]
So I think some android versions like MIUI or XOS don't allow any other clock app other than the system one to be opened by default. But I have implemented this, and it works on stock Android, so hopefully it also works on all versions that don't explicitly forbid it.

**Comment by AhsanSarwar45** [comment]
This should be working now in 0.3.1
