### ISSUE TITLE
App stays in foreground when phone is put to sleep

### ISSUE THREAD

**Issue by mizu-048** [vicolo-dev/chrono#89]
The apps stays in foreground when the phone goes to sleep/locks itself and when its turned on the app is in foreground, you can use the app as normal but quitting the app/pressing home, shows the lock screen as you should have been when waking the phone

**To Reproduce**
1. Open the app
2. Press the power button *screen turns off*
3. press the power button again *screen turns on* and you have the app infront of you instead of the lockscreen
4. Press back or home to make the lockscreen appear

**Expected behavior**
 i should see a lockscreen, which after i unlock shows the app

**Smartphone Information**
 - Device: [Sparx Neo 7]
 - OS: [Android 12]
 - App version [0.2.10]

**Comment by AhsanSarwar45** [comment]
This should be fixed in beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5. Please test it out to see if there are any issues.
