### ISSUE TITLE
Plese add a Backup option.

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#9]
Plese add All Setting Backup(export/import) option.

Too much customization options, all setting options backup must be added inside it.

**Comment by AhsanSarwar45** [comment]
Thanks for the idea. It actually turned out to be pretty simple to implement this. It will be out in the next release (0.2.8)

**Comment by AhsanSarwar45** [comment]
This feature is out now. Do test it and let me know if you find any issues.
