### ISSUE TITLE
Option to automatically delete alarm after dismiss

### ISSUE THREAD

**Issue by ltguillaume** [vicolo-dev/chrono#94]
**Is your feature request related to a problem? Please describe.**
I'm used to adding lots of one-time alarms. These can be removed automatically as soon as I have dismissed them.

**Describe the solution you'd like**
A per-alarm setting called "Delete after dismiss", which is also present under Settings > Alarm > Default Settings.

**Describe alternatives you've considered**
For reference, Simple Alarm Clock (https://github.com/yuriykulikov/AlarmClock) has this feature and it's great.

**Comment by Currrupted** [comment]
I agree! This would be very useful, especially since the option for a one-time alarm already exists.

**Comment by AhsanSarwar45** [comment]
Thanks, this has been added in v0.4.3. Feel free to create an issue if there are problems with it.
