### ISSUE TITLE
None of the settings are properly saved

### ISSUE THREAD

**Issue by ltguillaume** [vicolo-dev/chrono#96]
**Describe the bug**
Examples:
- When enabling "Show Instant Alarm Button", when I go back to alarms, it's present, but after an alarm has run, the setting is disabled again.
- When changing the Dismiss action type, the next time an alarm is going off, the action type is reset to the previous value.

**To Reproduce**
1. Go to Settings > Alarm > Dismiss Action Type
2. Note the previous type
3. Change to a new type
4. Close settings and go back to Settings > Alarm > Dismiss Action Type ==> you _do_ see the new action type
5. Create an alarm
6. Wait for the alarm and see the previous dismiss action type, instead of the new type.
7. Go back to Settings > Alarm > Dismiss Action Type ==> you see the previous action type

**Expected behavior**
Newly set preferences should be saved properly and not reset when the next alarm goes off.

**Smartphone Information**
 - Device: I4113
 - OS: Android 12
 - App version 0.2.10

**Additional context**
I've already cleared all app data and started anew to see if that would improve the situation. No dice.

It all looks to me like multiple activities are running concurrently and overwrite the settings: I often get to see the same screen of Chrono after pressing the Back button two or three times. This may also be related to #89.

**Comment by AhsanSarwar45** [comment]
So it only happens after alarm rings? If you change the setting, close the app (from recents too), and open it again, does the setting get saved in that case?

**Comment by AhsanSarwar45** [comment]
Alarms ringing randomly is a known issue that I am working on.

**Comment by AhsanSarwar45** [comment]
Hi, can you try with the latest beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5.
