### ISSUE TITLE
Temporarily disable an repeating alarm

### ISSUE THREAD

**Issue by UlyssesZh** [vicolo-dev/chrono#97]
**Is your feature request related to a problem? Please describe.**
Yesterday I waked up before the alarm went off, so I disabled the alarm, and I forgot to turn it on back again... I think a feature of temporarily disabling an alarm is very useful in this scenario.

**Describe the solution you'd like**
Show a button when the user disable an repeating alarm. If the button is triggered, the alarm will be enabled after the next time it would go off.

**Describe alternatives you've considered**

**Additional context**

**Comment by AhsanSarwar45** [comment]
Hi, if I understand correctly, this is same functionality as #67 right? If so, a feature to skip next alarm has been implemented and will come in the next update.

**Comment by UlyssesZh** [comment]
Yes. Thank you.
