### ISSUE TITLE
Auto start two timers

### ISSUE THREAD

**Issue by iBabu007** [vicolo-dev/chrono#98]
**Describe the bug**

**To Reproduce**
1. Go to 'timer'
2. Click on '45min/1hr timer'
3. See besides preset timers automatically runs and its previous saved time is missing and it replaced with 45m/1hr timer

If you have 3 deferent timer template
like 
30min
45min
1hr
And if you start 30min that is working but if you start 45min or 1hr then it started but it also started it's side template and make it 45 min or 1hr template.

**Smartphone Information**
 - Device: [micromax in 1]
 - OS: [e.g. Android 10]
 - App version [0. 2.10]

Uploading Screen-20240110-083550.mp4…

**Comment by Rafee-M** [comment]
The screen recording didn't get uploaded

**Comment by iBabu007** [comment]
https://github.com/vicolo-dev/chrono/assets/65340361/fd235228-0fc5-410d-8f22-71a2f9aa6cda

**Comment by AhsanSarwar45** [comment]
This should be fixed in beta release from github: https://github.com/vicolo-dev/chrono/releases/tag/v0.4.0-beta5. Please test it out to see if this issue persists.
