### ISSUE TITLE
chrono system appearance as clock app

### ISSUE THREAD

**Issue by Ruboka** [vicolo-dev/chrono#99]
I have the app warpclock for one time use alarms which get set by entering a time duration instead of a exact time after the alarm should go off. 
Now this app adds the alarm via installed clock apps(like the system default one ) or other apps 
Chrono does not appear in this list. 

I wonder if chrono needs to set a flag that Android lists it as a alarm time etc app in the system so other apps could find it that way?

**Comment by AhsanSarwar45** [comment]
This should be working now in 0.3.1
